package org.lyd.kmp01.designSystem.colors
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_blue_theme_primaryLight = Color(0xFF415F91)
val md_blue_theme_onPrimaryLight = Color(0xFFFFFFFF)
val md_blue_theme_primaryContainerLight = Color(0xFFD6E3FF)
val md_blue_theme_onPrimaryContainerLight = Color(0xFF001B3E)
val md_blue_theme_secondaryLight = Color(0xFF565F71)
val md_blue_theme_onSecondaryLight = Color(0xFFFFFFFF)
val md_blue_theme_secondaryContainerLight = Color(0xFFDAE2F9)
val md_blue_theme_onSecondaryContainerLight = Color(0xFF131C2B)
val md_blue_theme_tertiaryLight = Color(0xFF705575)
val md_blue_theme_onTertiaryLight = Color(0xFFFFFFFF)
val md_blue_theme_tertiaryContainerLight = Color(0xFFFAD8FD)
val md_blue_theme_onTertiaryContainerLight = Color(0xFF28132E)
val md_blue_theme_errorLight = Color(0xFFBA1A1A)
val md_blue_theme_onErrorLight = Color(0xFFFFFFFF)
val md_blue_theme_errorContainerLight = Color(0xFFFFDAD6)
val md_blue_theme_onErrorContainerLight = Color(0xFF410002)
val md_blue_theme_backgroundLight = Color(0xFFF9F9FF)
val md_blue_theme_onBackgroundLight = Color(0xFF191C20)
val md_blue_theme_surfaceLight = Color(0xFFF9F9FF)
val md_blue_theme_onSurfaceLight = Color(0xFF191C20)
val md_blue_theme_surfaceVariantLight = Color(0xFFE0E2EC)
val md_blue_theme_onSurfaceVariantLight = Color(0xFF44474E)
val md_blue_theme_outlineLight = Color(0xFF74777F)
val md_blue_theme_outlineVariantLight = Color(0xFFC4C6D0)
val md_blue_theme_scrimLight = Color(0xFF000000)
val md_blue_theme_inverseSurfaceLight = Color(0xFF2E3036)
val md_blue_theme_inverseOnSurfaceLight = Color(0xFFF0F0F7)
val md_blue_theme_inversePrimaryLight = Color(0xFFAAC7FF)
val md_blue_theme_surfaceDimLight = Color(0xFFD9D9E0)
val md_blue_theme_surfaceBrightLight = Color(0xFFF9F9FF)
val md_blue_theme_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val md_blue_theme_surfaceContainerLowLight = Color(0xFFF3F3FA)
val md_blue_theme_surfaceContainerLight = Color(0xFFEDEDF4)
val md_blue_theme_surfaceContainerHighLight = Color(0xFFE7E8EE)
val md_blue_theme_surfaceContainerHighestLight = Color(0xFFE2E2E9)

val md_blue_theme_primaryLightMediumContrast = Color(0xFF234373)
val md_blue_theme_onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_primaryContainerLightMediumContrast = Color(0xFF5875A8)
val md_blue_theme_onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_secondaryLightMediumContrast = Color(0xFF3A4354)
val md_blue_theme_onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_secondaryContainerLightMediumContrast = Color(0xFF6C7588)
val md_blue_theme_onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_tertiaryLightMediumContrast = Color(0xFF523A58)
val md_blue_theme_onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_tertiaryContainerLightMediumContrast = Color(0xFF876B8C)
val md_blue_theme_onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_errorLightMediumContrast = Color(0xFF8C0009)
val md_blue_theme_onErrorLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_errorContainerLightMediumContrast = Color(0xFFDA342E)
val md_blue_theme_onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_backgroundLightMediumContrast = Color(0xFFF9F9FF)
val md_blue_theme_onBackgroundLightMediumContrast = Color(0xFF191C20)
val md_blue_theme_surfaceLightMediumContrast = Color(0xFFF9F9FF)
val md_blue_theme_onSurfaceLightMediumContrast = Color(0xFF191C20)
val md_blue_theme_surfaceVariantLightMediumContrast = Color(0xFFE0E2EC)
val md_blue_theme_onSurfaceVariantLightMediumContrast = Color(0xFF40434A)
val md_blue_theme_outlineLightMediumContrast = Color(0xFF5C5F67)
val md_blue_theme_outlineVariantLightMediumContrast = Color(0xFF787A83)
val md_blue_theme_scrimLightMediumContrast = Color(0xFF000000)
val md_blue_theme_inverseSurfaceLightMediumContrast = Color(0xFF2E3036)
val md_blue_theme_inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
val md_blue_theme_inversePrimaryLightMediumContrast = Color(0xFFAAC7FF)
val md_blue_theme_surfaceDimLightMediumContrast = Color(0xFFD9D9E0)
val md_blue_theme_surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
val md_blue_theme_surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val md_blue_theme_surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
val md_blue_theme_surfaceContainerLightMediumContrast = Color(0xFFEDEDF4)
val md_blue_theme_surfaceContainerHighLightMediumContrast = Color(0xFFE7E8EE)
val md_blue_theme_surfaceContainerHighestLightMediumContrast = Color(0xFFE2E2E9)

val md_blue_theme_primaryLightHighContrast = Color(0xFF00214A)
val md_blue_theme_onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_primaryContainerLightHighContrast = Color(0xFF234373)
val md_blue_theme_onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_secondaryLightHighContrast = Color(0xFF192232)
val md_blue_theme_onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_secondaryContainerLightHighContrast = Color(0xFF3A4354)
val md_blue_theme_onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_tertiaryLightHighContrast = Color(0xFF301A35)
val md_blue_theme_onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_tertiaryContainerLightHighContrast = Color(0xFF523A58)
val md_blue_theme_onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_errorLightHighContrast = Color(0xFF4E0002)
val md_blue_theme_onErrorLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_errorContainerLightHighContrast = Color(0xFF8C0009)
val md_blue_theme_onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_backgroundLightHighContrast = Color(0xFFF9F9FF)
val md_blue_theme_onBackgroundLightHighContrast = Color(0xFF191C20)
val md_blue_theme_surfaceLightHighContrast = Color(0xFFF9F9FF)
val md_blue_theme_onSurfaceLightHighContrast = Color(0xFF000000)
val md_blue_theme_surfaceVariantLightHighContrast = Color(0xFFE0E2EC)
val md_blue_theme_onSurfaceVariantLightHighContrast = Color(0xFF21242B)
val md_blue_theme_outlineLightHighContrast = Color(0xFF40434A)
val md_blue_theme_outlineVariantLightHighContrast = Color(0xFF40434A)
val md_blue_theme_scrimLightHighContrast = Color(0xFF000000)
val md_blue_theme_inverseSurfaceLightHighContrast = Color(0xFF2E3036)
val md_blue_theme_inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_inversePrimaryLightHighContrast = Color(0xFFE5ECFF)
val md_blue_theme_surfaceDimLightHighContrast = Color(0xFFD9D9E0)
val md_blue_theme_surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
val md_blue_theme_surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_surfaceContainerLowLightHighContrast = Color(0xFFF3F3FA)
val md_blue_theme_surfaceContainerLightHighContrast = Color(0xFFEDEDF4)
val md_blue_theme_surfaceContainerHighLightHighContrast = Color(0xFFE7E8EE)
val md_blue_theme_surfaceContainerHighestLightHighContrast = Color(0xFFE2E2E9)

val md_blue_theme_primaryDark = Color(0xFFAAC7FF)
val md_blue_theme_onPrimaryDark = Color(0xFF0A305F)
val md_blue_theme_primaryContainerDark = Color(0xFF284777)
val md_blue_theme_onPrimaryContainerDark = Color(0xFFD6E3FF)
val md_blue_theme_secondaryDark = Color(0xFFBEC6DC)
val md_blue_theme_onSecondaryDark = Color(0xFF283141)
val md_blue_theme_secondaryContainerDark = Color(0xFF3E4759)
val md_blue_theme_onSecondaryContainerDark = Color(0xFFDAE2F9)
val md_blue_theme_tertiaryDark = Color(0xFFDDBCE0)
val md_blue_theme_onTertiaryDark = Color(0xFF3F2844)
val md_blue_theme_tertiaryContainerDark = Color(0xFF573E5C)
val md_blue_theme_onTertiaryContainerDark = Color(0xFFFAD8FD)
val md_blue_theme_errorDark = Color(0xFFFFB4AB)
val md_blue_theme_onErrorDark = Color(0xFF690005)
val md_blue_theme_errorContainerDark = Color(0xFF93000A)
val md_blue_theme_onErrorContainerDark = Color(0xFFFFDAD6)
val md_blue_theme_backgroundDark = Color(0xFF111318)
val md_blue_theme_onBackgroundDark = Color(0xFFE2E2E9)
val md_blue_theme_surfaceDark = Color(0xFF111318)
val md_blue_theme_onSurfaceDark = Color(0xFFE2E2E9)
val md_blue_theme_surfaceVariantDark = Color(0xFF44474E)
val md_blue_theme_onSurfaceVariantDark = Color(0xFFC4C6D0)
val md_blue_theme_outlineDark = Color(0xFF8E9099)
val md_blue_theme_outlineVariantDark = Color(0xFF44474E)
val md_blue_theme_scrimDark = Color(0xFF000000)
val md_blue_theme_inverseSurfaceDark = Color(0xFFE2E2E9)
val md_blue_theme_inverseOnSurfaceDark = Color(0xFF2E3036)
val md_blue_theme_inversePrimaryDark = Color(0xFF415F91)
val md_blue_theme_surfaceDimDark = Color(0xFF111318)
val md_blue_theme_surfaceBrightDark = Color(0xFF37393E)
val md_blue_theme_surfaceContainerLowestDark = Color(0xFF0C0E13)
val md_blue_theme_surfaceContainerLowDark = Color(0xFF191C20)
val md_blue_theme_surfaceContainerDark = Color(0xFF1D2024)
val md_blue_theme_surfaceContainerHighDark = Color(0xFF282A2F)
val md_blue_theme_surfaceContainerHighestDark = Color(0xFF33353A)

val md_blue_theme_primaryDarkMediumContrast = Color(0xFFB1CBFF)
val md_blue_theme_onPrimaryDarkMediumContrast = Color(0xFF001634)
val md_blue_theme_primaryContainerDarkMediumContrast = Color(0xFF7491C7)
val md_blue_theme_onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val md_blue_theme_secondaryDarkMediumContrast = Color(0xFFC2CBE0)
val md_blue_theme_onSecondaryDarkMediumContrast = Color(0xFF0D1626)
val md_blue_theme_secondaryContainerDarkMediumContrast = Color(0xFF8891A5)
val md_blue_theme_onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val md_blue_theme_tertiaryDarkMediumContrast = Color(0xFFE1C0E5)
val md_blue_theme_onTertiaryDarkMediumContrast = Color(0xFF230E29)
val md_blue_theme_tertiaryContainerDarkMediumContrast = Color(0xFFA487A9)
val md_blue_theme_onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val md_blue_theme_errorDarkMediumContrast = Color(0xFFFFBAB1)
val md_blue_theme_onErrorDarkMediumContrast = Color(0xFF370001)
val md_blue_theme_errorContainerDarkMediumContrast = Color(0xFFFF5449)
val md_blue_theme_onErrorContainerDarkMediumContrast = Color(0xFF000000)
val md_blue_theme_backgroundDarkMediumContrast = Color(0xFF111318)
val md_blue_theme_onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
val md_blue_theme_surfaceDarkMediumContrast = Color(0xFF111318)
val md_blue_theme_onSurfaceDarkMediumContrast = Color(0xFFFBFAFF)
val md_blue_theme_surfaceVariantDarkMediumContrast = Color(0xFF44474E)
val md_blue_theme_onSurfaceVariantDarkMediumContrast = Color(0xFFC8CAD4)
val md_blue_theme_outlineDarkMediumContrast = Color(0xFFA0A3AC)
val md_blue_theme_outlineVariantDarkMediumContrast = Color(0xFF80838C)
val md_blue_theme_scrimDarkMediumContrast = Color(0xFF000000)
val md_blue_theme_inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
val md_blue_theme_inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
val md_blue_theme_inversePrimaryDarkMediumContrast = Color(0xFF294878)
val md_blue_theme_surfaceDimDarkMediumContrast = Color(0xFF111318)
val md_blue_theme_surfaceBrightDarkMediumContrast = Color(0xFF37393E)
val md_blue_theme_surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0E13)
val md_blue_theme_surfaceContainerLowDarkMediumContrast = Color(0xFF191C20)
val md_blue_theme_surfaceContainerDarkMediumContrast = Color(0xFF1D2024)
val md_blue_theme_surfaceContainerHighDarkMediumContrast = Color(0xFF282A2F)
val md_blue_theme_surfaceContainerHighestDarkMediumContrast = Color(0xFF33353A)

val md_blue_theme_primaryDarkHighContrast = Color(0xFFFBFAFF)
val md_blue_theme_onPrimaryDarkHighContrast = Color(0xFF000000)
val md_blue_theme_primaryContainerDarkHighContrast = Color(0xFFB1CBFF)
val md_blue_theme_onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val md_blue_theme_secondaryDarkHighContrast = Color(0xFFFBFAFF)
val md_blue_theme_onSecondaryDarkHighContrast = Color(0xFF000000)
val md_blue_theme_secondaryContainerDarkHighContrast = Color(0xFFC2CBE0)
val md_blue_theme_onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val md_blue_theme_tertiaryDarkHighContrast = Color(0xFFFFF9FA)
val md_blue_theme_onTertiaryDarkHighContrast = Color(0xFF000000)
val md_blue_theme_tertiaryContainerDarkHighContrast = Color(0xFFE1C0E5)
val md_blue_theme_onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val md_blue_theme_errorDarkHighContrast = Color(0xFFFFF9F9)
val md_blue_theme_onErrorDarkHighContrast = Color(0xFF000000)
val md_blue_theme_errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val md_blue_theme_onErrorContainerDarkHighContrast = Color(0xFF000000)
val md_blue_theme_backgroundDarkHighContrast = Color(0xFF111318)
val md_blue_theme_onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
val md_blue_theme_surfaceDarkHighContrast = Color(0xFF111318)
val md_blue_theme_onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val md_blue_theme_surfaceVariantDarkHighContrast = Color(0xFF44474E)
val md_blue_theme_onSurfaceVariantDarkHighContrast = Color(0xFFFBFAFF)
val md_blue_theme_outlineDarkHighContrast = Color(0xFFC8CAD4)
val md_blue_theme_outlineVariantDarkHighContrast = Color(0xFFC8CAD4)
val md_blue_theme_scrimDarkHighContrast = Color(0xFF000000)
val md_blue_theme_inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
val md_blue_theme_inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val md_blue_theme_inversePrimaryDarkHighContrast = Color(0xFF002959)
val md_blue_theme_surfaceDimDarkHighContrast = Color(0xFF111318)
val md_blue_theme_surfaceBrightDarkHighContrast = Color(0xFF37393E)
val md_blue_theme_surfaceContainerLowestDarkHighContrast = Color(0xFF0C0E13)
val md_blue_theme_surfaceContainerLowDarkHighContrast = Color(0xFF191C20)
val md_blue_theme_surfaceContainerDarkHighContrast = Color(0xFF1D2024)
val md_blue_theme_surfaceContainerHighDarkHighContrast = Color(0xFF282A2F)
val md_blue_theme_surfaceContainerHighestDarkHighContrast = Color(0xFF33353A)

val BlueLightScheme = lightColorScheme(
    primary = md_blue_theme_primaryLight,
    onPrimary = md_blue_theme_onPrimaryLight,
    primaryContainer = md_blue_theme_primaryContainerLight,
    onPrimaryContainer = md_blue_theme_onPrimaryContainerLight,
    secondary = md_blue_theme_secondaryLight,
    onSecondary = md_blue_theme_onSecondaryLight,
    secondaryContainer = md_blue_theme_secondaryContainerLight,
    onSecondaryContainer = md_blue_theme_onSecondaryContainerLight,
    tertiary = md_blue_theme_tertiaryLight,
    onTertiary = md_blue_theme_onTertiaryLight,
    tertiaryContainer = md_blue_theme_tertiaryContainerLight,
    onTertiaryContainer = md_blue_theme_onTertiaryContainerLight,
    error = md_blue_theme_errorLight,
    onError = md_blue_theme_onErrorLight,
    errorContainer = md_blue_theme_errorContainerLight,
    onErrorContainer = md_blue_theme_onErrorContainerLight,
    background = md_blue_theme_backgroundLight,
    onBackground = md_blue_theme_onBackgroundLight,
    surface = md_blue_theme_surfaceLight,
    onSurface = md_blue_theme_onSurfaceLight,
    surfaceVariant = md_blue_theme_surfaceVariantLight,
    onSurfaceVariant = md_blue_theme_onSurfaceVariantLight,
    outline = md_blue_theme_outlineLight,
    outlineVariant = md_blue_theme_outlineVariantLight,
    scrim = md_blue_theme_scrimLight,
    inverseSurface = md_blue_theme_inverseSurfaceLight,
    inverseOnSurface = md_blue_theme_inverseOnSurfaceLight,
    inversePrimary = md_blue_theme_inversePrimaryLight,
    surfaceDim = md_blue_theme_surfaceDimLight,
    surfaceBright = md_blue_theme_surfaceBrightLight,
    surfaceContainerLowest = md_blue_theme_surfaceContainerLowestLight,
    surfaceContainerLow = md_blue_theme_surfaceContainerLowLight,
    surfaceContainer = md_blue_theme_surfaceContainerLight,
    surfaceContainerHigh = md_blue_theme_surfaceContainerHighLight,
    surfaceContainerHighest = md_blue_theme_surfaceContainerHighestLight,
)

val BlueDarkScheme = darkColorScheme(
    primary = md_blue_theme_primaryDark,
    onPrimary = md_blue_theme_onPrimaryDark,
    primaryContainer = md_blue_theme_primaryContainerDark,
    onPrimaryContainer = md_blue_theme_onPrimaryContainerDark,
    secondary = md_blue_theme_secondaryDark,
    onSecondary = md_blue_theme_onSecondaryDark,
    secondaryContainer = md_blue_theme_secondaryContainerDark,
    onSecondaryContainer = md_blue_theme_onSecondaryContainerDark,
    tertiary = md_blue_theme_tertiaryDark,
    onTertiary = md_blue_theme_onTertiaryDark,
    tertiaryContainer = md_blue_theme_tertiaryContainerDark,
    onTertiaryContainer = md_blue_theme_onTertiaryContainerDark,
    error = md_blue_theme_errorDark,
    onError = md_blue_theme_onErrorDark,
    errorContainer = md_blue_theme_errorContainerDark,
    onErrorContainer = md_blue_theme_onErrorContainerDark,
    background = md_blue_theme_backgroundDark,
    onBackground = md_blue_theme_onBackgroundDark,
    surface = md_blue_theme_surfaceDark,
    onSurface = md_blue_theme_onSurfaceDark,
    surfaceVariant = md_blue_theme_surfaceVariantDark,
    onSurfaceVariant = md_blue_theme_onSurfaceVariantDark,
    outline = md_blue_theme_outlineDark,
    outlineVariant = md_blue_theme_outlineVariantDark,
    scrim = md_blue_theme_scrimDark,
    inverseSurface = md_blue_theme_inverseSurfaceDark,
    inverseOnSurface = md_blue_theme_inverseOnSurfaceDark,
    inversePrimary = md_blue_theme_inversePrimaryDark,
    surfaceDim = md_blue_theme_surfaceDimDark,
    surfaceBright = md_blue_theme_surfaceBrightDark,
    surfaceContainerLowest = md_blue_theme_surfaceContainerLowestDark,
    surfaceContainerLow = md_blue_theme_surfaceContainerLowDark,
    surfaceContainer = md_blue_theme_surfaceContainerDark,
    surfaceContainerHigh = md_blue_theme_surfaceContainerHighDark,
    surfaceContainerHighest = md_blue_theme_surfaceContainerHighestDark,
)

val BlueMediumContrastLightColorScheme = lightColorScheme(
    primary = md_blue_theme_primaryLightMediumContrast,
    onPrimary = md_blue_theme_onPrimaryLightMediumContrast,
    primaryContainer = md_blue_theme_primaryContainerLightMediumContrast,
    onPrimaryContainer = md_blue_theme_onPrimaryContainerLightMediumContrast,
    secondary = md_blue_theme_secondaryLightMediumContrast,
    onSecondary = md_blue_theme_onSecondaryLightMediumContrast,
    secondaryContainer = md_blue_theme_secondaryContainerLightMediumContrast,
    onSecondaryContainer = md_blue_theme_onSecondaryContainerLightMediumContrast,
    tertiary = md_blue_theme_tertiaryLightMediumContrast,
    onTertiary = md_blue_theme_onTertiaryLightMediumContrast,
    tertiaryContainer = md_blue_theme_tertiaryContainerLightMediumContrast,
    onTertiaryContainer = md_blue_theme_onTertiaryContainerLightMediumContrast,
    error = md_blue_theme_errorLightMediumContrast,
    onError = md_blue_theme_onErrorLightMediumContrast,
    errorContainer = md_blue_theme_errorContainerLightMediumContrast,
    onErrorContainer = md_blue_theme_onErrorContainerLightMediumContrast,
    background = md_blue_theme_backgroundLightMediumContrast,
    onBackground = md_blue_theme_onBackgroundLightMediumContrast,
    surface = md_blue_theme_surfaceLightMediumContrast,
    onSurface = md_blue_theme_onSurfaceLightMediumContrast,
    surfaceVariant = md_blue_theme_surfaceVariantLightMediumContrast,
    onSurfaceVariant = md_blue_theme_onSurfaceVariantLightMediumContrast,
    outline = md_blue_theme_outlineLightMediumContrast,
    outlineVariant = md_blue_theme_outlineVariantLightMediumContrast,
    scrim = md_blue_theme_scrimLightMediumContrast,
    inverseSurface = md_blue_theme_inverseSurfaceLightMediumContrast,
    inverseOnSurface = md_blue_theme_inverseOnSurfaceLightMediumContrast,
    inversePrimary = md_blue_theme_inversePrimaryLightMediumContrast,
    surfaceDim = md_blue_theme_surfaceDimLightMediumContrast,
    surfaceBright = md_blue_theme_surfaceBrightLightMediumContrast,
    surfaceContainerLowest = md_blue_theme_surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = md_blue_theme_surfaceContainerLowLightMediumContrast,
    surfaceContainer = md_blue_theme_surfaceContainerLightMediumContrast,
    surfaceContainerHigh = md_blue_theme_surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = md_blue_theme_surfaceContainerHighestLightMediumContrast,
)

val BlueHighContrastLightColorScheme = lightColorScheme(
    primary = md_blue_theme_primaryLightHighContrast,
    onPrimary = md_blue_theme_onPrimaryLightHighContrast,
    primaryContainer = md_blue_theme_primaryContainerLightHighContrast,
    onPrimaryContainer = md_blue_theme_onPrimaryContainerLightHighContrast,
    secondary = md_blue_theme_secondaryLightHighContrast,
    onSecondary = md_blue_theme_onSecondaryLightHighContrast,
    secondaryContainer = md_blue_theme_secondaryContainerLightHighContrast,
    onSecondaryContainer = md_blue_theme_onSecondaryContainerLightHighContrast,
    tertiary = md_blue_theme_tertiaryLightHighContrast,
    onTertiary = md_blue_theme_onTertiaryLightHighContrast,
    tertiaryContainer = md_blue_theme_tertiaryContainerLightHighContrast,
    onTertiaryContainer = md_blue_theme_onTertiaryContainerLightHighContrast,
    error = md_blue_theme_errorLightHighContrast,
    onError = md_blue_theme_onErrorLightHighContrast,
    errorContainer = md_blue_theme_errorContainerLightHighContrast,
    onErrorContainer = md_blue_theme_onErrorContainerLightHighContrast,
    background = md_blue_theme_backgroundLightHighContrast,
    onBackground = md_blue_theme_onBackgroundLightHighContrast,
    surface = md_blue_theme_surfaceLightHighContrast,
    onSurface = md_blue_theme_onSurfaceLightHighContrast,
    surfaceVariant = md_blue_theme_surfaceVariantLightHighContrast,
    onSurfaceVariant = md_blue_theme_onSurfaceVariantLightHighContrast,
    outline = md_blue_theme_outlineLightHighContrast,
    outlineVariant = md_blue_theme_outlineVariantLightHighContrast,
    scrim = md_blue_theme_scrimLightHighContrast,
    inverseSurface = md_blue_theme_inverseSurfaceLightHighContrast,
    inverseOnSurface = md_blue_theme_inverseOnSurfaceLightHighContrast,
    inversePrimary = md_blue_theme_inversePrimaryLightHighContrast,
    surfaceDim = md_blue_theme_surfaceDimLightHighContrast,
    surfaceBright = md_blue_theme_surfaceBrightLightHighContrast,
    surfaceContainerLowest = md_blue_theme_surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = md_blue_theme_surfaceContainerLowLightHighContrast,
    surfaceContainer = md_blue_theme_surfaceContainerLightHighContrast,
    surfaceContainerHigh = md_blue_theme_surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = md_blue_theme_surfaceContainerHighestLightHighContrast,
)

val BlueMediumContrastDarkColorScheme = darkColorScheme(
    primary = md_blue_theme_primaryDarkMediumContrast,
    onPrimary = md_blue_theme_onPrimaryDarkMediumContrast,
    primaryContainer = md_blue_theme_primaryContainerDarkMediumContrast,
    onPrimaryContainer = md_blue_theme_onPrimaryContainerDarkMediumContrast,
    secondary = md_blue_theme_secondaryDarkMediumContrast,
    onSecondary = md_blue_theme_onSecondaryDarkMediumContrast,
    secondaryContainer = md_blue_theme_secondaryContainerDarkMediumContrast,
    onSecondaryContainer = md_blue_theme_onSecondaryContainerDarkMediumContrast,
    tertiary = md_blue_theme_tertiaryDarkMediumContrast,
    onTertiary = md_blue_theme_onTertiaryDarkMediumContrast,
    tertiaryContainer = md_blue_theme_tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = md_blue_theme_onTertiaryContainerDarkMediumContrast,
    error = md_blue_theme_errorDarkMediumContrast,
    onError = md_blue_theme_onErrorDarkMediumContrast,
    errorContainer = md_blue_theme_errorContainerDarkMediumContrast,
    onErrorContainer = md_blue_theme_onErrorContainerDarkMediumContrast,
    background = md_blue_theme_backgroundDarkMediumContrast,
    onBackground = md_blue_theme_onBackgroundDarkMediumContrast,
    surface = md_blue_theme_surfaceDarkMediumContrast,
    onSurface = md_blue_theme_onSurfaceDarkMediumContrast,
    surfaceVariant = md_blue_theme_surfaceVariantDarkMediumContrast,
    onSurfaceVariant = md_blue_theme_onSurfaceVariantDarkMediumContrast,
    outline = md_blue_theme_outlineDarkMediumContrast,
    outlineVariant = md_blue_theme_outlineVariantDarkMediumContrast,
    scrim = md_blue_theme_scrimDarkMediumContrast,
    inverseSurface = md_blue_theme_inverseSurfaceDarkMediumContrast,
    inverseOnSurface = md_blue_theme_inverseOnSurfaceDarkMediumContrast,
    inversePrimary = md_blue_theme_inversePrimaryDarkMediumContrast,
    surfaceDim = md_blue_theme_surfaceDimDarkMediumContrast,
    surfaceBright = md_blue_theme_surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = md_blue_theme_surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = md_blue_theme_surfaceContainerLowDarkMediumContrast,
    surfaceContainer = md_blue_theme_surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = md_blue_theme_surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = md_blue_theme_surfaceContainerHighestDarkMediumContrast,
)

val BlueHighContrastDarkColorScheme = darkColorScheme(
    primary = md_blue_theme_primaryDarkHighContrast,
    onPrimary = md_blue_theme_onPrimaryDarkHighContrast,
    primaryContainer = md_blue_theme_primaryContainerDarkHighContrast,
    onPrimaryContainer = md_blue_theme_onPrimaryContainerDarkHighContrast,
    secondary = md_blue_theme_secondaryDarkHighContrast,
    onSecondary = md_blue_theme_onSecondaryDarkHighContrast,
    secondaryContainer = md_blue_theme_secondaryContainerDarkHighContrast,
    onSecondaryContainer = md_blue_theme_onSecondaryContainerDarkHighContrast,
    tertiary = md_blue_theme_tertiaryDarkHighContrast,
    onTertiary = md_blue_theme_onTertiaryDarkHighContrast,
    tertiaryContainer = md_blue_theme_tertiaryContainerDarkHighContrast,
    onTertiaryContainer = md_blue_theme_onTertiaryContainerDarkHighContrast,
    error = md_blue_theme_errorDarkHighContrast,
    onError = md_blue_theme_onErrorDarkHighContrast,
    errorContainer = md_blue_theme_errorContainerDarkHighContrast,
    onErrorContainer = md_blue_theme_onErrorContainerDarkHighContrast,
    background = md_blue_theme_backgroundDarkHighContrast,
    onBackground = md_blue_theme_onBackgroundDarkHighContrast,
    surface = md_blue_theme_surfaceDarkHighContrast,
    onSurface = md_blue_theme_onSurfaceDarkHighContrast,
    surfaceVariant = md_blue_theme_surfaceVariantDarkHighContrast,
    onSurfaceVariant = md_blue_theme_onSurfaceVariantDarkHighContrast,
    outline = md_blue_theme_outlineDarkHighContrast,
    outlineVariant = md_blue_theme_outlineVariantDarkHighContrast,
    scrim = md_blue_theme_scrimDarkHighContrast,
    inverseSurface = md_blue_theme_inverseSurfaceDarkHighContrast,
    inverseOnSurface = md_blue_theme_inverseOnSurfaceDarkHighContrast,
    inversePrimary = md_blue_theme_inversePrimaryDarkHighContrast,
    surfaceDim = md_blue_theme_surfaceDimDarkHighContrast,
    surfaceBright = md_blue_theme_surfaceBrightDarkHighContrast,
    surfaceContainerLowest = md_blue_theme_surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = md_blue_theme_surfaceContainerLowDarkHighContrast,
    surfaceContainer = md_blue_theme_surfaceContainerDarkHighContrast,
    surfaceContainerHigh = md_blue_theme_surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = md_blue_theme_surfaceContainerHighestDarkHighContrast,
)

