package org.lyd.kmp01.designSystem.colors

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_green_theme_primaryLight = Color(0xFF4C662B)
val md_green_theme_onPrimaryLight = Color(0xFFFFFFFF)
val md_green_theme_primaryContainerLight = Color(0xFFCDEDA3)
val md_green_theme_onPrimaryContainerLight = Color(0xFF102000)
val md_green_theme_secondaryLight = Color(0xFF586249)
val md_green_theme_onSecondaryLight = Color(0xFFFFFFFF)
val md_green_theme_secondaryContainerLight = Color(0xFFDCE7C8)
val md_green_theme_onSecondaryContainerLight = Color(0xFF151E0B)
val md_green_theme_tertiaryLight = Color(0xFF386663)
val md_green_theme_onTertiaryLight = Color(0xFFFFFFFF)
val md_green_theme_tertiaryContainerLight = Color(0xFFBCECE7)
val md_green_theme_onTertiaryContainerLight = Color(0xFF00201E)
val md_green_theme_errorLight = Color(0xFFBA1A1A)
val md_green_theme_onErrorLight = Color(0xFFFFFFFF)
val md_green_theme_errorContainerLight = Color(0xFFFFDAD6)
val md_green_theme_onErrorContainerLight = Color(0xFF410002)
val md_green_theme_backgroundLight = Color(0xFFF9FAEF)
val md_green_theme_onBackgroundLight = Color(0xFF1A1C16)
val md_green_theme_surfaceLight = Color(0xFFF9FAEF)
val md_green_theme_onSurfaceLight = Color(0xFF1A1C16)
val md_green_theme_surfaceVariantLight = Color(0xFFE1E4D5)
val md_green_theme_onSurfaceVariantLight = Color(0xFF44483D)
val md_green_theme_outlineLight = Color(0xFF75796C)
val md_green_theme_outlineVariantLight = Color(0xFFC5C8BA)
val md_green_theme_scrimLight = Color(0xFF000000)
val md_green_theme_inverseSurfaceLight = Color(0xFF2F312A)
val md_green_theme_inverseOnSurfaceLight = Color(0xFFF1F2E6)
val md_green_theme_inversePrimaryLight = Color(0xFFB1D18A)
val md_green_theme_surfaceDimLight = Color(0xFFDADBD0)
val md_green_theme_surfaceBrightLight = Color(0xFFF9FAEF)
val md_green_theme_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val md_green_theme_surfaceContainerLowLight = Color(0xFFF3F4E9)
val md_green_theme_surfaceContainerLight = Color(0xFFEEEFE3)
val md_green_theme_surfaceContainerHighLight = Color(0xFFE8E9DE)
val md_green_theme_surfaceContainerHighestLight = Color(0xFFE2E3D8)

val md_green_theme_primaryLightMediumContrast = Color(0xFF314A12)
val md_green_theme_onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_primaryContainerLightMediumContrast = Color(0xFF617D3F)
val md_green_theme_onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_secondaryLightMediumContrast = Color(0xFF3C462F)
val md_green_theme_onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_secondaryContainerLightMediumContrast = Color(0xFF6E785E)
val md_green_theme_onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_tertiaryLightMediumContrast = Color(0xFF1A4A47)
val md_green_theme_onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_tertiaryContainerLightMediumContrast = Color(0xFF4F7D79)
val md_green_theme_onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_errorLightMediumContrast = Color(0xFF8C0009)
val md_green_theme_onErrorLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_errorContainerLightMediumContrast = Color(0xFFDA342E)
val md_green_theme_onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_backgroundLightMediumContrast = Color(0xFFF9FAEF)
val md_green_theme_onBackgroundLightMediumContrast = Color(0xFF1A1C16)
val md_green_theme_surfaceLightMediumContrast = Color(0xFFF9FAEF)
val md_green_theme_onSurfaceLightMediumContrast = Color(0xFF1A1C16)
val md_green_theme_surfaceVariantLightMediumContrast = Color(0xFFE1E4D5)
val md_green_theme_onSurfaceVariantLightMediumContrast = Color(0xFF404439)
val md_green_theme_outlineLightMediumContrast = Color(0xFF5D6155)
val md_green_theme_outlineVariantLightMediumContrast = Color(0xFF787C70)
val md_green_theme_scrimLightMediumContrast = Color(0xFF000000)
val md_green_theme_inverseSurfaceLightMediumContrast = Color(0xFF2F312A)
val md_green_theme_inverseOnSurfaceLightMediumContrast = Color(0xFFF1F2E6)
val md_green_theme_inversePrimaryLightMediumContrast = Color(0xFFB1D18A)
val md_green_theme_surfaceDimLightMediumContrast = Color(0xFFDADBD0)
val md_green_theme_surfaceBrightLightMediumContrast = Color(0xFFF9FAEF)
val md_green_theme_surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val md_green_theme_surfaceContainerLowLightMediumContrast = Color(0xFFF3F4E9)
val md_green_theme_surfaceContainerLightMediumContrast = Color(0xFFEEEFE3)
val md_green_theme_surfaceContainerHighLightMediumContrast = Color(0xFFE8E9DE)
val md_green_theme_surfaceContainerHighestLightMediumContrast = Color(0xFFE2E3D8)

val md_green_theme_primaryLightHighContrast = Color(0xFF142700)
val md_green_theme_onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_primaryContainerLightHighContrast = Color(0xFF314A12)
val md_green_theme_onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_secondaryLightHighContrast = Color(0xFF1C2511)
val md_green_theme_onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_secondaryContainerLightHighContrast = Color(0xFF3C462F)
val md_green_theme_onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_tertiaryLightHighContrast = Color(0xFF002725)
val md_green_theme_onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_tertiaryContainerLightHighContrast = Color(0xFF1A4A47)
val md_green_theme_onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_errorLightHighContrast = Color(0xFF4E0002)
val md_green_theme_onErrorLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_errorContainerLightHighContrast = Color(0xFF8C0009)
val md_green_theme_onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_backgroundLightHighContrast = Color(0xFFF9FAEF)
val md_green_theme_onBackgroundLightHighContrast = Color(0xFF1A1C16)
val md_green_theme_surfaceLightHighContrast = Color(0xFFF9FAEF)
val md_green_theme_onSurfaceLightHighContrast = Color(0xFF000000)
val md_green_theme_surfaceVariantLightHighContrast = Color(0xFFE1E4D5)
val md_green_theme_onSurfaceVariantLightHighContrast = Color(0xFF21251C)
val md_green_theme_outlineLightHighContrast = Color(0xFF404439)
val md_green_theme_outlineVariantLightHighContrast = Color(0xFF404439)
val md_green_theme_scrimLightHighContrast = Color(0xFF000000)
val md_green_theme_inverseSurfaceLightHighContrast = Color(0xFF2F312A)
val md_green_theme_inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_inversePrimaryLightHighContrast = Color(0xFFD6F7AC)
val md_green_theme_surfaceDimLightHighContrast = Color(0xFFDADBD0)
val md_green_theme_surfaceBrightLightHighContrast = Color(0xFFF9FAEF)
val md_green_theme_surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val md_green_theme_surfaceContainerLowLightHighContrast = Color(0xFFF3F4E9)
val md_green_theme_surfaceContainerLightHighContrast = Color(0xFFEEEFE3)
val md_green_theme_surfaceContainerHighLightHighContrast = Color(0xFFE8E9DE)
val md_green_theme_surfaceContainerHighestLightHighContrast = Color(0xFFE2E3D8)

val md_green_theme_primaryDark = Color(0xFFB1D18A)
val md_green_theme_onPrimaryDark = Color(0xFF1F3701)
val md_green_theme_primaryContainerDark = Color(0xFF354E16)
val md_green_theme_onPrimaryContainerDark = Color(0xFFCDEDA3)
val md_green_theme_secondaryDark = Color(0xFFBFCBAD)
val md_green_theme_onSecondaryDark = Color(0xFF2A331E)
val md_green_theme_secondaryContainerDark = Color(0xFF404A33)
val md_green_theme_onSecondaryContainerDark = Color(0xFFDCE7C8)
val md_green_theme_tertiaryDark = Color(0xFFA0D0CB)
val md_green_theme_onTertiaryDark = Color(0xFF003735)
val md_green_theme_tertiaryContainerDark = Color(0xFF1F4E4B)
val md_green_theme_onTertiaryContainerDark = Color(0xFFBCECE7)
val md_green_theme_errorDark = Color(0xFFFFB4AB)
val md_green_theme_onErrorDark = Color(0xFF690005)
val md_green_theme_errorContainerDark = Color(0xFF93000A)
val md_green_theme_onErrorContainerDark = Color(0xFFFFDAD6)
val md_green_theme_backgroundDark = Color(0xFF12140E)
val md_green_theme_onBackgroundDark = Color(0xFFE2E3D8)
val md_green_theme_surfaceDark = Color(0xFF12140E)
val md_green_theme_onSurfaceDark = Color(0xFFE2E3D8)
val md_green_theme_surfaceVariantDark = Color(0xFF44483D)
val md_green_theme_onSurfaceVariantDark = Color(0xFFC5C8BA)
val md_green_theme_outlineDark = Color(0xFF8F9285)
val md_green_theme_outlineVariantDark = Color(0xFF44483D)
val md_green_theme_scrimDark = Color(0xFF000000)
val md_green_theme_inverseSurfaceDark = Color(0xFFE2E3D8)
val md_green_theme_inverseOnSurfaceDark = Color(0xFF2F312A)
val md_green_theme_inversePrimaryDark = Color(0xFF4C662B)
val md_green_theme_surfaceDimDark = Color(0xFF12140E)
val md_green_theme_surfaceBrightDark = Color(0xFF383A32)
val md_green_theme_surfaceContainerLowestDark = Color(0xFF0C0F09)
val md_green_theme_surfaceContainerLowDark = Color(0xFF1A1C16)
val md_green_theme_surfaceContainerDark = Color(0xFF1E201A)
val md_green_theme_surfaceContainerHighDark = Color(0xFF282B24)
val md_green_theme_surfaceContainerHighestDark = Color(0xFF33362E)

val md_green_theme_primaryDarkMediumContrast = Color(0xFFB5D58E)
val md_green_theme_onPrimaryDarkMediumContrast = Color(0xFF0C1A00)
val md_green_theme_primaryContainerDarkMediumContrast = Color(0xFF7D9A59)
val md_green_theme_onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val md_green_theme_secondaryDarkMediumContrast = Color(0xFFC4CFB1)
val md_green_theme_onSecondaryDarkMediumContrast = Color(0xFF101907)
val md_green_theme_secondaryContainerDarkMediumContrast = Color(0xFF8A9579)
val md_green_theme_onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val md_green_theme_tertiaryDarkMediumContrast = Color(0xFFA4D4D0)
val md_green_theme_onTertiaryDarkMediumContrast = Color(0xFF001A19)
val md_green_theme_tertiaryContainerDarkMediumContrast = Color(0xFF6B9995)
val md_green_theme_onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val md_green_theme_errorDarkMediumContrast = Color(0xFFFFBAB1)
val md_green_theme_onErrorDarkMediumContrast = Color(0xFF370001)
val md_green_theme_errorContainerDarkMediumContrast = Color(0xFFFF5449)
val md_green_theme_onErrorContainerDarkMediumContrast = Color(0xFF000000)
val md_green_theme_backgroundDarkMediumContrast = Color(0xFF12140E)
val md_green_theme_onBackgroundDarkMediumContrast = Color(0xFFE2E3D8)
val md_green_theme_surfaceDarkMediumContrast = Color(0xFF12140E)
val md_green_theme_onSurfaceDarkMediumContrast = Color(0xFFFBFCF0)
val md_green_theme_surfaceVariantDarkMediumContrast = Color(0xFF44483D)
val md_green_theme_onSurfaceVariantDarkMediumContrast = Color(0xFFC9CCBE)
val md_green_theme_outlineDarkMediumContrast = Color(0xFFA1A497)
val md_green_theme_outlineVariantDarkMediumContrast = Color(0xFF818578)
val md_green_theme_scrimDarkMediumContrast = Color(0xFF000000)
val md_green_theme_inverseSurfaceDarkMediumContrast = Color(0xFFE2E3D8)
val md_green_theme_inverseOnSurfaceDarkMediumContrast = Color(0xFF282B24)
val md_green_theme_inversePrimaryDarkMediumContrast = Color(0xFF364F17)
val md_green_theme_surfaceDimDarkMediumContrast = Color(0xFF12140E)
val md_green_theme_surfaceBrightDarkMediumContrast = Color(0xFF383A32)
val md_green_theme_surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0F09)
val md_green_theme_surfaceContainerLowDarkMediumContrast = Color(0xFF1A1C16)
val md_green_theme_surfaceContainerDarkMediumContrast = Color(0xFF1E201A)
val md_green_theme_surfaceContainerHighDarkMediumContrast = Color(0xFF282B24)
val md_green_theme_surfaceContainerHighestDarkMediumContrast = Color(0xFF33362E)

val md_green_theme_primaryDarkHighContrast = Color(0xFFF4FFDF)
val md_green_theme_onPrimaryDarkHighContrast = Color(0xFF000000)
val md_green_theme_primaryContainerDarkHighContrast = Color(0xFFB5D58E)
val md_green_theme_onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val md_green_theme_secondaryDarkHighContrast = Color(0xFFF4FFDF)
val md_green_theme_onSecondaryDarkHighContrast = Color(0xFF000000)
val md_green_theme_secondaryContainerDarkHighContrast = Color(0xFFC4CFB1)
val md_green_theme_onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val md_green_theme_tertiaryDarkHighContrast = Color(0xFFEAFFFC)
val md_green_theme_onTertiaryDarkHighContrast = Color(0xFF000000)
val md_green_theme_tertiaryContainerDarkHighContrast = Color(0xFFA4D4D0)
val md_green_theme_onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val md_green_theme_errorDarkHighContrast = Color(0xFFFFF9F9)
val md_green_theme_onErrorDarkHighContrast = Color(0xFF000000)
val md_green_theme_errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val md_green_theme_onErrorContainerDarkHighContrast = Color(0xFF000000)
val md_green_theme_backgroundDarkHighContrast = Color(0xFF12140E)
val md_green_theme_onBackgroundDarkHighContrast = Color(0xFFE2E3D8)
val md_green_theme_surfaceDarkHighContrast = Color(0xFF12140E)
val md_green_theme_onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val md_green_theme_surfaceVariantDarkHighContrast = Color(0xFF44483D)
val md_green_theme_onSurfaceVariantDarkHighContrast = Color(0xFFF9FCED)
val md_green_theme_outlineDarkHighContrast = Color(0xFFC9CCBE)
val md_green_theme_outlineVariantDarkHighContrast = Color(0xFFC9CCBE)
val md_green_theme_scrimDarkHighContrast = Color(0xFF000000)
val md_green_theme_inverseSurfaceDarkHighContrast = Color(0xFFE2E3D8)
val md_green_theme_inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val md_green_theme_inversePrimaryDarkHighContrast = Color(0xFF1A3000)
val md_green_theme_surfaceDimDarkHighContrast = Color(0xFF12140E)
val md_green_theme_surfaceBrightDarkHighContrast = Color(0xFF383A32)
val md_green_theme_surfaceContainerLowestDarkHighContrast = Color(0xFF0C0F09)
val md_green_theme_surfaceContainerLowDarkHighContrast = Color(0xFF1A1C16)
val md_green_theme_surfaceContainerDarkHighContrast = Color(0xFF1E201A)
val md_green_theme_surfaceContainerHighDarkHighContrast = Color(0xFF282B24)
val md_green_theme_surfaceContainerHighestDarkHighContrast = Color(0xFF33362E)

val GreenLightScheme = lightColorScheme(
    primary = md_green_theme_primaryLight,
    onPrimary = md_green_theme_onPrimaryLight,
    primaryContainer = md_green_theme_primaryContainerLight,
    onPrimaryContainer = md_green_theme_onPrimaryContainerLight,
    secondary = md_green_theme_secondaryLight,
    onSecondary = md_green_theme_onSecondaryLight,
    secondaryContainer = md_green_theme_secondaryContainerLight,
    onSecondaryContainer = md_green_theme_onSecondaryContainerLight,
    tertiary = md_green_theme_tertiaryLight,
    onTertiary = md_green_theme_onTertiaryLight,
    tertiaryContainer = md_green_theme_tertiaryContainerLight,
    onTertiaryContainer = md_green_theme_onTertiaryContainerLight,
    error = md_green_theme_errorLight,
    onError = md_green_theme_onErrorLight,
    errorContainer = md_green_theme_errorContainerLight,
    onErrorContainer = md_green_theme_onErrorContainerLight,
    background = md_green_theme_backgroundLight,
    onBackground = md_green_theme_onBackgroundLight,
    surface = md_green_theme_surfaceLight,
    onSurface = md_green_theme_onSurfaceLight,
    surfaceVariant = md_green_theme_surfaceVariantLight,
    onSurfaceVariant = md_green_theme_onSurfaceVariantLight,
    outline = md_green_theme_outlineLight,
    outlineVariant = md_green_theme_outlineVariantLight,
    scrim = md_green_theme_scrimLight,
    inverseSurface = md_green_theme_inverseSurfaceLight,
    inverseOnSurface = md_green_theme_inverseOnSurfaceLight,
    inversePrimary = md_green_theme_inversePrimaryLight,
    surfaceDim = md_green_theme_surfaceDimLight,
    surfaceBright = md_green_theme_surfaceBrightLight,
    surfaceContainerLowest = md_green_theme_surfaceContainerLowestLight,
    surfaceContainerLow = md_green_theme_surfaceContainerLowLight,
    surfaceContainer = md_green_theme_surfaceContainerLight,
    surfaceContainerHigh = md_green_theme_surfaceContainerHighLight,
    surfaceContainerHighest = md_green_theme_surfaceContainerHighestLight,
)

val GreenDarkScheme = darkColorScheme(
    primary = md_green_theme_primaryDark,
    onPrimary = md_green_theme_onPrimaryDark,
    primaryContainer = md_green_theme_primaryContainerDark,
    onPrimaryContainer = md_green_theme_onPrimaryContainerDark,
    secondary = md_green_theme_secondaryDark,
    onSecondary = md_green_theme_onSecondaryDark,
    secondaryContainer = md_green_theme_secondaryContainerDark,
    onSecondaryContainer = md_green_theme_onSecondaryContainerDark,
    tertiary = md_green_theme_tertiaryDark,
    onTertiary = md_green_theme_onTertiaryDark,
    tertiaryContainer = md_green_theme_tertiaryContainerDark,
    onTertiaryContainer = md_green_theme_onTertiaryContainerDark,
    error = md_green_theme_errorDark,
    onError = md_green_theme_onErrorDark,
    errorContainer = md_green_theme_errorContainerDark,
    onErrorContainer = md_green_theme_onErrorContainerDark,
    background = md_green_theme_backgroundDark,
    onBackground = md_green_theme_onBackgroundDark,
    surface = md_green_theme_surfaceDark,
    onSurface = md_green_theme_onSurfaceDark,
    surfaceVariant = md_green_theme_surfaceVariantDark,
    onSurfaceVariant = md_green_theme_onSurfaceVariantDark,
    outline = md_green_theme_outlineDark,
    outlineVariant = md_green_theme_outlineVariantDark,
    scrim = md_green_theme_scrimDark,
    inverseSurface = md_green_theme_inverseSurfaceDark,
    inverseOnSurface = md_green_theme_inverseOnSurfaceDark,
    inversePrimary = md_green_theme_inversePrimaryDark,
    surfaceDim = md_green_theme_surfaceDimDark,
    surfaceBright = md_green_theme_surfaceBrightDark,
    surfaceContainerLowest = md_green_theme_surfaceContainerLowestDark,
    surfaceContainerLow = md_green_theme_surfaceContainerLowDark,
    surfaceContainer = md_green_theme_surfaceContainerDark,
    surfaceContainerHigh = md_green_theme_surfaceContainerHighDark,
    surfaceContainerHighest = md_green_theme_surfaceContainerHighestDark,
)

val GreenMediumContrastLightColorScheme = lightColorScheme(
    primary = md_green_theme_primaryLightMediumContrast,
    onPrimary = md_green_theme_onPrimaryLightMediumContrast,
    primaryContainer = md_green_theme_primaryContainerLightMediumContrast,
    onPrimaryContainer = md_green_theme_onPrimaryContainerLightMediumContrast,
    secondary = md_green_theme_secondaryLightMediumContrast,
    onSecondary = md_green_theme_onSecondaryLightMediumContrast,
    secondaryContainer = md_green_theme_secondaryContainerLightMediumContrast,
    onSecondaryContainer = md_green_theme_onSecondaryContainerLightMediumContrast,
    tertiary = md_green_theme_tertiaryLightMediumContrast,
    onTertiary = md_green_theme_onTertiaryLightMediumContrast,
    tertiaryContainer = md_green_theme_tertiaryContainerLightMediumContrast,
    onTertiaryContainer = md_green_theme_onTertiaryContainerLightMediumContrast,
    error = md_green_theme_errorLightMediumContrast,
    onError = md_green_theme_onErrorLightMediumContrast,
    errorContainer = md_green_theme_errorContainerLightMediumContrast,
    onErrorContainer = md_green_theme_onErrorContainerLightMediumContrast,
    background = md_green_theme_backgroundLightMediumContrast,
    onBackground = md_green_theme_onBackgroundLightMediumContrast,
    surface = md_green_theme_surfaceLightMediumContrast,
    onSurface = md_green_theme_onSurfaceLightMediumContrast,
    surfaceVariant = md_green_theme_surfaceVariantLightMediumContrast,
    onSurfaceVariant = md_green_theme_onSurfaceVariantLightMediumContrast,
    outline = md_green_theme_outlineLightMediumContrast,
    outlineVariant = md_green_theme_outlineVariantLightMediumContrast,
    scrim = md_green_theme_scrimLightMediumContrast,
    inverseSurface = md_green_theme_inverseSurfaceLightMediumContrast,
    inverseOnSurface = md_green_theme_inverseOnSurfaceLightMediumContrast,
    inversePrimary = md_green_theme_inversePrimaryLightMediumContrast,
    surfaceDim = md_green_theme_surfaceDimLightMediumContrast,
    surfaceBright = md_green_theme_surfaceBrightLightMediumContrast,
    surfaceContainerLowest = md_green_theme_surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = md_green_theme_surfaceContainerLowLightMediumContrast,
    surfaceContainer = md_green_theme_surfaceContainerLightMediumContrast,
    surfaceContainerHigh = md_green_theme_surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = md_green_theme_surfaceContainerHighestLightMediumContrast,
)

val GreenHighContrastLightColorScheme = lightColorScheme(
    primary = md_green_theme_primaryLightHighContrast,
    onPrimary = md_green_theme_onPrimaryLightHighContrast,
    primaryContainer = md_green_theme_primaryContainerLightHighContrast,
    onPrimaryContainer = md_green_theme_onPrimaryContainerLightHighContrast,
    secondary = md_green_theme_secondaryLightHighContrast,
    onSecondary = md_green_theme_onSecondaryLightHighContrast,
    secondaryContainer = md_green_theme_secondaryContainerLightHighContrast,
    onSecondaryContainer = md_green_theme_onSecondaryContainerLightHighContrast,
    tertiary = md_green_theme_tertiaryLightHighContrast,
    onTertiary = md_green_theme_onTertiaryLightHighContrast,
    tertiaryContainer = md_green_theme_tertiaryContainerLightHighContrast,
    onTertiaryContainer = md_green_theme_onTertiaryContainerLightHighContrast,
    error = md_green_theme_errorLightHighContrast,
    onError = md_green_theme_onErrorLightHighContrast,
    errorContainer = md_green_theme_errorContainerLightHighContrast,
    onErrorContainer = md_green_theme_onErrorContainerLightHighContrast,
    background = md_green_theme_backgroundLightHighContrast,
    onBackground = md_green_theme_onBackgroundLightHighContrast,
    surface = md_green_theme_surfaceLightHighContrast,
    onSurface = md_green_theme_onSurfaceLightHighContrast,
    surfaceVariant = md_green_theme_surfaceVariantLightHighContrast,
    onSurfaceVariant = md_green_theme_onSurfaceVariantLightHighContrast,
    outline = md_green_theme_outlineLightHighContrast,
    outlineVariant = md_green_theme_outlineVariantLightHighContrast,
    scrim = md_green_theme_scrimLightHighContrast,
    inverseSurface = md_green_theme_inverseSurfaceLightHighContrast,
    inverseOnSurface = md_green_theme_inverseOnSurfaceLightHighContrast,
    inversePrimary = md_green_theme_inversePrimaryLightHighContrast,
    surfaceDim = md_green_theme_surfaceDimLightHighContrast,
    surfaceBright = md_green_theme_surfaceBrightLightHighContrast,
    surfaceContainerLowest = md_green_theme_surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = md_green_theme_surfaceContainerLowLightHighContrast,
    surfaceContainer = md_green_theme_surfaceContainerLightHighContrast,
    surfaceContainerHigh = md_green_theme_surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = md_green_theme_surfaceContainerHighestLightHighContrast,
)

val GreenMediumContrastDarkColorScheme = darkColorScheme(
    primary = md_green_theme_primaryDarkMediumContrast,
    onPrimary = md_green_theme_onPrimaryDarkMediumContrast,
    primaryContainer = md_green_theme_primaryContainerDarkMediumContrast,
    onPrimaryContainer = md_green_theme_onPrimaryContainerDarkMediumContrast,
    secondary = md_green_theme_secondaryDarkMediumContrast,
    onSecondary = md_green_theme_onSecondaryDarkMediumContrast,
    secondaryContainer = md_green_theme_secondaryContainerDarkMediumContrast,
    onSecondaryContainer = md_green_theme_onSecondaryContainerDarkMediumContrast,
    tertiary = md_green_theme_tertiaryDarkMediumContrast,
    onTertiary = md_green_theme_onTertiaryDarkMediumContrast,
    tertiaryContainer = md_green_theme_tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = md_green_theme_onTertiaryContainerDarkMediumContrast,
    error = md_green_theme_errorDarkMediumContrast,
    onError = md_green_theme_onErrorDarkMediumContrast,
    errorContainer = md_green_theme_errorContainerDarkMediumContrast,
    onErrorContainer = md_green_theme_onErrorContainerDarkMediumContrast,
    background = md_green_theme_backgroundDarkMediumContrast,
    onBackground = md_green_theme_onBackgroundDarkMediumContrast,
    surface = md_green_theme_surfaceDarkMediumContrast,
    onSurface = md_green_theme_onSurfaceDarkMediumContrast,
    surfaceVariant = md_green_theme_surfaceVariantDarkMediumContrast,
    onSurfaceVariant = md_green_theme_onSurfaceVariantDarkMediumContrast,
    outline = md_green_theme_outlineDarkMediumContrast,
    outlineVariant = md_green_theme_outlineVariantDarkMediumContrast,
    scrim = md_green_theme_scrimDarkMediumContrast,
    inverseSurface = md_green_theme_inverseSurfaceDarkMediumContrast,
    inverseOnSurface = md_green_theme_inverseOnSurfaceDarkMediumContrast,
    inversePrimary = md_green_theme_inversePrimaryDarkMediumContrast,
    surfaceDim = md_green_theme_surfaceDimDarkMediumContrast,
    surfaceBright = md_green_theme_surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = md_green_theme_surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = md_green_theme_surfaceContainerLowDarkMediumContrast,
    surfaceContainer = md_green_theme_surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = md_green_theme_surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = md_green_theme_surfaceContainerHighestDarkMediumContrast,
)

val GreenHighContrastDarkColorScheme = darkColorScheme(
    primary = md_green_theme_primaryDarkHighContrast,
    onPrimary = md_green_theme_onPrimaryDarkHighContrast,
    primaryContainer = md_green_theme_primaryContainerDarkHighContrast,
    onPrimaryContainer = md_green_theme_onPrimaryContainerDarkHighContrast,
    secondary = md_green_theme_secondaryDarkHighContrast,
    onSecondary = md_green_theme_onSecondaryDarkHighContrast,
    secondaryContainer = md_green_theme_secondaryContainerDarkHighContrast,
    onSecondaryContainer = md_green_theme_onSecondaryContainerDarkHighContrast,
    tertiary = md_green_theme_tertiaryDarkHighContrast,
    onTertiary = md_green_theme_onTertiaryDarkHighContrast,
    tertiaryContainer = md_green_theme_tertiaryContainerDarkHighContrast,
    onTertiaryContainer = md_green_theme_onTertiaryContainerDarkHighContrast,
    error = md_green_theme_errorDarkHighContrast,
    onError = md_green_theme_onErrorDarkHighContrast,
    errorContainer = md_green_theme_errorContainerDarkHighContrast,
    onErrorContainer = md_green_theme_onErrorContainerDarkHighContrast,
    background = md_green_theme_backgroundDarkHighContrast,
    onBackground = md_green_theme_onBackgroundDarkHighContrast,
    surface = md_green_theme_surfaceDarkHighContrast,
    onSurface = md_green_theme_onSurfaceDarkHighContrast,
    surfaceVariant = md_green_theme_surfaceVariantDarkHighContrast,
    onSurfaceVariant = md_green_theme_onSurfaceVariantDarkHighContrast,
    outline = md_green_theme_outlineDarkHighContrast,
    outlineVariant = md_green_theme_outlineVariantDarkHighContrast,
    scrim = md_green_theme_scrimDarkHighContrast,
    inverseSurface = md_green_theme_inverseSurfaceDarkHighContrast,
    inverseOnSurface = md_green_theme_inverseOnSurfaceDarkHighContrast,
    inversePrimary = md_green_theme_inversePrimaryDarkHighContrast,
    surfaceDim = md_green_theme_surfaceDimDarkHighContrast,
    surfaceBright = md_green_theme_surfaceBrightDarkHighContrast,
    surfaceContainerLowest = md_green_theme_surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = md_green_theme_surfaceContainerLowDarkHighContrast,
    surfaceContainer = md_green_theme_surfaceContainerDarkHighContrast,
    surfaceContainerHigh = md_green_theme_surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = md_green_theme_surfaceContainerHighestDarkHighContrast,
)


