package org.lyd.kmp01.designSystem.colors

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_red_theme_primaryLight = Color(0xFF8F4C38)
val md_red_theme_onPrimaryLight = Color(0xFFFFFFFF)
val md_red_theme_primaryContainerLight = Color(0xFFFFDBD1)
val md_red_theme_onPrimaryContainerLight = Color(0xFF3A0B01)
val md_red_theme_secondaryLight = Color(0xFF77574E)
val md_red_theme_onSecondaryLight = Color(0xFFFFFFFF)
val md_red_theme_secondaryContainerLight = Color(0xFFFFDBD1)
val md_red_theme_onSecondaryContainerLight = Color(0xFF2C150F)
val md_red_theme_tertiaryLight = Color(0xFF6C5D2F)
val md_red_theme_onTertiaryLight = Color(0xFFFFFFFF)
val md_red_theme_tertiaryContainerLight = Color(0xFFF5E1A7)
val md_red_theme_onTertiaryContainerLight = Color(0xFF231B00)
val md_red_theme_errorLight = Color(0xFFBA1A1A)
val md_red_theme_onErrorLight = Color(0xFFFFFFFF)
val md_red_theme_errorContainerLight = Color(0xFFFFDAD6)
val md_red_theme_onErrorContainerLight = Color(0xFF410002)
val md_red_theme_backgroundLight = Color(0xFFFFF8F6)
val md_red_theme_onBackgroundLight = Color(0xFF231917)
val md_red_theme_surfaceLight = Color(0xFFFFF8F6)
val md_red_theme_onSurfaceLight = Color(0xFF231917)
val md_red_theme_surfaceVariantLight = Color(0xFFF5DED8)
val md_red_theme_onSurfaceVariantLight = Color(0xFF53433F)
val md_red_theme_outlineLight = Color(0xFF85736E)
val md_red_theme_outlineVariantLight = Color(0xFFD8C2BC)
val md_red_theme_scrimLight = Color(0xFF000000)
val md_red_theme_inverseSurfaceLight = Color(0xFF392E2B)
val md_red_theme_inverseOnSurfaceLight = Color(0xFFFFEDE8)
val md_red_theme_inversePrimaryLight = Color(0xFFFFB5A0)
val md_red_theme_surfaceDimLight = Color(0xFFE8D6D2)
val md_red_theme_surfaceBrightLight = Color(0xFFFFF8F6)
val md_red_theme_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val md_red_theme_surfaceContainerLowLight = Color(0xFFFFF1ED)
val md_red_theme_surfaceContainerLight = Color(0xFFFCEAE5)
val md_red_theme_surfaceContainerHighLight = Color(0xFFF7E4E0)
val md_red_theme_surfaceContainerHighestLight = Color(0xFFF1DFDA)

val md_red_theme_primaryLightMediumContrast = Color(0xFF6D311F)
val md_red_theme_onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_primaryContainerLightMediumContrast = Color(0xFFAA614C)
val md_red_theme_onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_secondaryLightMediumContrast = Color(0xFF593C34)
val md_red_theme_onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_secondaryContainerLightMediumContrast = Color(0xFF8F6D63)
val md_red_theme_onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_tertiaryLightMediumContrast = Color(0xFF4E4216)
val md_red_theme_onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_tertiaryContainerLightMediumContrast = Color(0xFF837442)
val md_red_theme_onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_errorLightMediumContrast = Color(0xFF8C0009)
val md_red_theme_onErrorLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_errorContainerLightMediumContrast = Color(0xFFDA342E)
val md_red_theme_onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_backgroundLightMediumContrast = Color(0xFFFFF8F6)
val md_red_theme_onBackgroundLightMediumContrast = Color(0xFF231917)
val md_red_theme_surfaceLightMediumContrast = Color(0xFFFFF8F6)
val md_red_theme_onSurfaceLightMediumContrast = Color(0xFF231917)
val md_red_theme_surfaceVariantLightMediumContrast = Color(0xFFF5DED8)
val md_red_theme_onSurfaceVariantLightMediumContrast = Color(0xFF4F3F3B)
val md_red_theme_outlineLightMediumContrast = Color(0xFF6C5B57)
val md_red_theme_outlineVariantLightMediumContrast = Color(0xFF897772)
val md_red_theme_scrimLightMediumContrast = Color(0xFF000000)
val md_red_theme_inverseSurfaceLightMediumContrast = Color(0xFF392E2B)
val md_red_theme_inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE8)
val md_red_theme_inversePrimaryLightMediumContrast = Color(0xFFFFB5A0)
val md_red_theme_surfaceDimLightMediumContrast = Color(0xFFE8D6D2)
val md_red_theme_surfaceBrightLightMediumContrast = Color(0xFFFFF8F6)
val md_red_theme_surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val md_red_theme_surfaceContainerLowLightMediumContrast = Color(0xFFFFF1ED)
val md_red_theme_surfaceContainerLightMediumContrast = Color(0xFFFCEAE5)
val md_red_theme_surfaceContainerHighLightMediumContrast = Color(0xFFF7E4E0)
val md_red_theme_surfaceContainerHighestLightMediumContrast = Color(0xFFF1DFDA)

val md_red_theme_primaryLightHighContrast = Color(0xFF431104)
val md_red_theme_onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_primaryContainerLightHighContrast = Color(0xFF6D311F)
val md_red_theme_onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_secondaryLightHighContrast = Color(0xFF341C15)
val md_red_theme_onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_secondaryContainerLightHighContrast = Color(0xFF593C34)
val md_red_theme_onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_tertiaryLightHighContrast = Color(0xFF2B2100)
val md_red_theme_onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_tertiaryContainerLightHighContrast = Color(0xFF4E4216)
val md_red_theme_onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_errorLightHighContrast = Color(0xFF4E0002)
val md_red_theme_onErrorLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_errorContainerLightHighContrast = Color(0xFF8C0009)
val md_red_theme_onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_backgroundLightHighContrast = Color(0xFFFFF8F6)
val md_red_theme_onBackgroundLightHighContrast = Color(0xFF231917)
val md_red_theme_surfaceLightHighContrast = Color(0xFFFFF8F6)
val md_red_theme_onSurfaceLightHighContrast = Color(0xFF000000)
val md_red_theme_surfaceVariantLightHighContrast = Color(0xFFF5DED8)
val md_red_theme_onSurfaceVariantLightHighContrast = Color(0xFF2E211D)
val md_red_theme_outlineLightHighContrast = Color(0xFF4F3F3B)
val md_red_theme_outlineVariantLightHighContrast = Color(0xFF4F3F3B)
val md_red_theme_scrimLightHighContrast = Color(0xFF000000)
val md_red_theme_inverseSurfaceLightHighContrast = Color(0xFF392E2B)
val md_red_theme_inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_inversePrimaryLightHighContrast = Color(0xFFFFE7E1)
val md_red_theme_surfaceDimLightHighContrast = Color(0xFFE8D6D2)
val md_red_theme_surfaceBrightLightHighContrast = Color(0xFFFFF8F6)
val md_red_theme_surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val md_red_theme_surfaceContainerLowLightHighContrast = Color(0xFFFFF1ED)
val md_red_theme_surfaceContainerLightHighContrast = Color(0xFFFCEAE5)
val md_red_theme_surfaceContainerHighLightHighContrast = Color(0xFFF7E4E0)
val md_red_theme_surfaceContainerHighestLightHighContrast = Color(0xFFF1DFDA)

val md_red_theme_primaryDark = Color(0xFFFFB5A0)
val md_red_theme_onPrimaryDark = Color(0xFF561F0F)
val md_red_theme_primaryContainerDark = Color(0xFF723523)
val md_red_theme_onPrimaryContainerDark = Color(0xFFFFDBD1)
val md_red_theme_secondaryDark = Color(0xFFE7BDB2)
val md_red_theme_onSecondaryDark = Color(0xFF442A22)
val md_red_theme_secondaryContainerDark = Color(0xFF5D4037)
val md_red_theme_onSecondaryContainerDark = Color(0xFFFFDBD1)
val md_red_theme_tertiaryDark = Color(0xFFD8C58D)
val md_red_theme_onTertiaryDark = Color(0xFF3B2F05)
val md_red_theme_tertiaryContainerDark = Color(0xFF534619)
val md_red_theme_onTertiaryContainerDark = Color(0xFFF5E1A7)
val md_red_theme_errorDark = Color(0xFFFFB4AB)
val md_red_theme_onErrorDark = Color(0xFF690005)
val md_red_theme_errorContainerDark = Color(0xFF93000A)
val md_red_theme_onErrorContainerDark = Color(0xFFFFDAD6)
val md_red_theme_backgroundDark = Color(0xFF1A110F)
val md_red_theme_onBackgroundDark = Color(0xFFF1DFDA)
val md_red_theme_surfaceDark = Color(0xFF1A110F)
val md_red_theme_onSurfaceDark = Color(0xFFF1DFDA)
val md_red_theme_surfaceVariantDark = Color(0xFF53433F)
val md_red_theme_onSurfaceVariantDark = Color(0xFFD8C2BC)
val md_red_theme_outlineDark = Color(0xFFA08C87)
val md_red_theme_outlineVariantDark = Color(0xFF53433F)
val md_red_theme_scrimDark = Color(0xFF000000)
val md_red_theme_inverseSurfaceDark = Color(0xFFF1DFDA)
val md_red_theme_inverseOnSurfaceDark = Color(0xFF392E2B)
val md_red_theme_inversePrimaryDark = Color(0xFF8F4C38)
val md_red_theme_surfaceDimDark = Color(0xFF1A110F)
val md_red_theme_surfaceBrightDark = Color(0xFF423734)
val md_red_theme_surfaceContainerLowestDark = Color(0xFF140C0A)
val md_red_theme_surfaceContainerLowDark = Color(0xFF231917)
val md_red_theme_surfaceContainerDark = Color(0xFF271D1B)
val md_red_theme_surfaceContainerHighDark = Color(0xFF322825)
val md_red_theme_surfaceContainerHighestDark = Color(0xFF3D322F)

val md_red_theme_primaryDarkMediumContrast = Color(0xFFFFBBA7)
val md_red_theme_onPrimaryDarkMediumContrast = Color(0xFF310700)
val md_red_theme_primaryContainerDarkMediumContrast = Color(0xFFCB7C65)
val md_red_theme_onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val md_red_theme_secondaryDarkMediumContrast = Color(0xFFECC1B6)
val md_red_theme_onSecondaryDarkMediumContrast = Color(0xFF26100A)
val md_red_theme_secondaryContainerDarkMediumContrast = Color(0xFFAE887E)
val md_red_theme_onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val md_red_theme_tertiaryDarkMediumContrast = Color(0xFFDDCA91)
val md_red_theme_onTertiaryDarkMediumContrast = Color(0xFF1D1600)
val md_red_theme_tertiaryContainerDarkMediumContrast = Color(0xFFA0905C)
val md_red_theme_onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val md_red_theme_errorDarkMediumContrast = Color(0xFFFFBAB1)
val md_red_theme_onErrorDarkMediumContrast = Color(0xFF370001)
val md_red_theme_errorContainerDarkMediumContrast = Color(0xFFFF5449)
val md_red_theme_onErrorContainerDarkMediumContrast = Color(0xFF000000)
val md_red_theme_backgroundDarkMediumContrast = Color(0xFF1A110F)
val md_red_theme_onBackgroundDarkMediumContrast = Color(0xFFF1DFDA)
val md_red_theme_surfaceDarkMediumContrast = Color(0xFF1A110F)
val md_red_theme_onSurfaceDarkMediumContrast = Color(0xFFFFF9F8)
val md_red_theme_surfaceVariantDarkMediumContrast = Color(0xFF53433F)
val md_red_theme_onSurfaceVariantDarkMediumContrast = Color(0xFFDCC6C0)
val md_red_theme_outlineDarkMediumContrast = Color(0xFFB39E99)
val md_red_theme_outlineVariantDarkMediumContrast = Color(0xFF927F7A)
val md_red_theme_scrimDarkMediumContrast = Color(0xFF000000)
val md_red_theme_inverseSurfaceDarkMediumContrast = Color(0xFFF1DFDA)
val md_red_theme_inverseOnSurfaceDarkMediumContrast = Color(0xFF322825)
val md_red_theme_inversePrimaryDarkMediumContrast = Color(0xFF743624)
val md_red_theme_surfaceDimDarkMediumContrast = Color(0xFF1A110F)
val md_red_theme_surfaceBrightDarkMediumContrast = Color(0xFF423734)
val md_red_theme_surfaceContainerLowestDarkMediumContrast = Color(0xFF140C0A)
val md_red_theme_surfaceContainerLowDarkMediumContrast = Color(0xFF231917)
val md_red_theme_surfaceContainerDarkMediumContrast = Color(0xFF271D1B)
val md_red_theme_surfaceContainerHighDarkMediumContrast = Color(0xFF322825)
val md_red_theme_surfaceContainerHighestDarkMediumContrast = Color(0xFF3D322F)

val md_red_theme_primaryDarkHighContrast = Color(0xFFFFF9F8)
val md_red_theme_onPrimaryDarkHighContrast = Color(0xFF000000)
val md_red_theme_primaryContainerDarkHighContrast = Color(0xFFFFBBA7)
val md_red_theme_onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val md_red_theme_secondaryDarkHighContrast = Color(0xFFFFF9F8)
val md_red_theme_onSecondaryDarkHighContrast = Color(0xFF000000)
val md_red_theme_secondaryContainerDarkHighContrast = Color(0xFFECC1B6)
val md_red_theme_onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val md_red_theme_tertiaryDarkHighContrast = Color(0xFFFFFAF6)
val md_red_theme_onTertiaryDarkHighContrast = Color(0xFF000000)
val md_red_theme_tertiaryContainerDarkHighContrast = Color(0xFFDDCA91)
val md_red_theme_onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val md_red_theme_errorDarkHighContrast = Color(0xFFFFF9F9)
val md_red_theme_onErrorDarkHighContrast = Color(0xFF000000)
val md_red_theme_errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val md_red_theme_onErrorContainerDarkHighContrast = Color(0xFF000000)
val md_red_theme_backgroundDarkHighContrast = Color(0xFF1A110F)
val md_red_theme_onBackgroundDarkHighContrast = Color(0xFFF1DFDA)
val md_red_theme_surfaceDarkHighContrast = Color(0xFF1A110F)
val md_red_theme_onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val md_red_theme_surfaceVariantDarkHighContrast = Color(0xFF53433F)
val md_red_theme_onSurfaceVariantDarkHighContrast = Color(0xFFFFF9F8)
val md_red_theme_outlineDarkHighContrast = Color(0xFFDCC6C0)
val md_red_theme_outlineVariantDarkHighContrast = Color(0xFFDCC6C0)
val md_red_theme_scrimDarkHighContrast = Color(0xFF000000)
val md_red_theme_inverseSurfaceDarkHighContrast = Color(0xFFF1DFDA)
val md_red_theme_inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val md_red_theme_inversePrimaryDarkHighContrast = Color(0xFF4D1909)
val md_red_theme_surfaceDimDarkHighContrast = Color(0xFF1A110F)
val md_red_theme_surfaceBrightDarkHighContrast = Color(0xFF423734)
val md_red_theme_surfaceContainerLowestDarkHighContrast = Color(0xFF140C0A)
val md_red_theme_surfaceContainerLowDarkHighContrast = Color(0xFF231917)
val md_red_theme_surfaceContainerDarkHighContrast = Color(0xFF271D1B)
val md_red_theme_surfaceContainerHighDarkHighContrast = Color(0xFF322825)
val md_red_theme_surfaceContainerHighestDarkHighContrast = Color(0xFF3D322F)


val RedLightScheme = lightColorScheme(
    primary = md_red_theme_primaryLight,
    onPrimary = md_red_theme_onPrimaryLight,
    primaryContainer = md_red_theme_primaryContainerLight,
    onPrimaryContainer = md_red_theme_onPrimaryContainerLight,
    secondary = md_red_theme_secondaryLight,
    onSecondary = md_red_theme_onSecondaryLight,
    secondaryContainer = md_red_theme_secondaryContainerLight,
    onSecondaryContainer = md_red_theme_onSecondaryContainerLight,
    tertiary = md_red_theme_tertiaryLight,
    onTertiary = md_red_theme_onTertiaryLight,
    tertiaryContainer = md_red_theme_tertiaryContainerLight,
    onTertiaryContainer = md_red_theme_onTertiaryContainerLight,
    error = md_red_theme_errorLight,
    onError = md_red_theme_onErrorLight,
    errorContainer = md_red_theme_errorContainerLight,
    onErrorContainer = md_red_theme_onErrorContainerLight,
    background = md_red_theme_backgroundLight,
    onBackground = md_red_theme_onBackgroundLight,
    surface = md_red_theme_surfaceLight,
    onSurface = md_red_theme_onSurfaceLight,
    surfaceVariant = md_red_theme_surfaceVariantLight,
    onSurfaceVariant = md_red_theme_onSurfaceVariantLight,
    outline = md_red_theme_outlineLight,
    outlineVariant = md_red_theme_outlineVariantLight,
    scrim = md_red_theme_scrimLight,
    inverseSurface = md_red_theme_inverseSurfaceLight,
    inverseOnSurface = md_red_theme_inverseOnSurfaceLight,
    inversePrimary = md_red_theme_inversePrimaryLight,
    surfaceDim = md_red_theme_surfaceDimLight,
    surfaceBright = md_red_theme_surfaceBrightLight,
    surfaceContainerLowest = md_red_theme_surfaceContainerLowestLight,
    surfaceContainerLow = md_red_theme_surfaceContainerLowLight,
    surfaceContainer = md_red_theme_surfaceContainerLight,
    surfaceContainerHigh = md_red_theme_surfaceContainerHighLight,
    surfaceContainerHighest = md_red_theme_surfaceContainerHighestLight,
)

val RedDarkScheme = darkColorScheme(
    primary = md_red_theme_primaryDark,
    onPrimary = md_red_theme_onPrimaryDark,
    primaryContainer = md_red_theme_primaryContainerDark,
    onPrimaryContainer = md_red_theme_onPrimaryContainerDark,
    secondary = md_red_theme_secondaryDark,
    onSecondary = md_red_theme_onSecondaryDark,
    secondaryContainer = md_red_theme_secondaryContainerDark,
    onSecondaryContainer = md_red_theme_onSecondaryContainerDark,
    tertiary = md_red_theme_tertiaryDark,
    onTertiary = md_red_theme_onTertiaryDark,
    tertiaryContainer = md_red_theme_tertiaryContainerDark,
    onTertiaryContainer = md_red_theme_onTertiaryContainerDark,
    error = md_red_theme_errorDark,
    onError = md_red_theme_onErrorDark,
    errorContainer = md_red_theme_errorContainerDark,
    onErrorContainer = md_red_theme_onErrorContainerDark,
    background = md_red_theme_backgroundDark,
    onBackground = md_red_theme_onBackgroundDark,
    surface = md_red_theme_surfaceDark,
    onSurface = md_red_theme_onSurfaceDark,
    surfaceVariant = md_red_theme_surfaceVariantDark,
    onSurfaceVariant = md_red_theme_onSurfaceVariantDark,
    outline = md_red_theme_outlineDark,
    outlineVariant = md_red_theme_outlineVariantDark,
    scrim = md_red_theme_scrimDark,
    inverseSurface = md_red_theme_inverseSurfaceDark,
    inverseOnSurface = md_red_theme_inverseOnSurfaceDark,
    inversePrimary = md_red_theme_inversePrimaryDark,
    surfaceDim = md_red_theme_surfaceDimDark,
    surfaceBright = md_red_theme_surfaceBrightDark,
    surfaceContainerLowest = md_red_theme_surfaceContainerLowestDark,
    surfaceContainerLow = md_red_theme_surfaceContainerLowDark,
    surfaceContainer = md_red_theme_surfaceContainerDark,
    surfaceContainerHigh = md_red_theme_surfaceContainerHighDark,
    surfaceContainerHighest = md_red_theme_surfaceContainerHighestDark,
)

val RedMediumContrastLightScheme = lightColorScheme(
    primary = md_red_theme_primaryLightMediumContrast,
    onPrimary = md_red_theme_onPrimaryLightMediumContrast,
    primaryContainer = md_red_theme_primaryContainerLightMediumContrast,
    onPrimaryContainer = md_red_theme_onPrimaryContainerLightMediumContrast,
    secondary = md_red_theme_secondaryLightMediumContrast,
    onSecondary = md_red_theme_onSecondaryLightMediumContrast,
    secondaryContainer = md_red_theme_secondaryContainerLightMediumContrast,
    onSecondaryContainer = md_red_theme_onSecondaryContainerLightMediumContrast,
    tertiary = md_red_theme_tertiaryLightMediumContrast,
    onTertiary = md_red_theme_onTertiaryLightMediumContrast,
    tertiaryContainer = md_red_theme_tertiaryContainerLightMediumContrast,
    onTertiaryContainer = md_red_theme_onTertiaryContainerLightMediumContrast,
    error = md_red_theme_errorLightMediumContrast,
    onError = md_red_theme_onErrorLightMediumContrast,
    errorContainer = md_red_theme_errorContainerLightMediumContrast,
    onErrorContainer = md_red_theme_onErrorContainerLightMediumContrast,
    background = md_red_theme_backgroundLightMediumContrast,
    onBackground = md_red_theme_onBackgroundLightMediumContrast,
    surface = md_red_theme_surfaceLightMediumContrast,
    onSurface = md_red_theme_onSurfaceLightMediumContrast,
    surfaceVariant = md_red_theme_surfaceVariantLightMediumContrast,
    onSurfaceVariant = md_red_theme_onSurfaceVariantLightMediumContrast,
    outline = md_red_theme_outlineLightMediumContrast,
    outlineVariant = md_red_theme_outlineVariantLightMediumContrast,
    scrim = md_red_theme_scrimLightMediumContrast,
    inverseSurface = md_red_theme_inverseSurfaceLightMediumContrast,
    inverseOnSurface = md_red_theme_inverseOnSurfaceLightMediumContrast,
    inversePrimary = md_red_theme_inversePrimaryLightMediumContrast,
    surfaceDim = md_red_theme_surfaceDimLightMediumContrast,
    surfaceBright = md_red_theme_surfaceBrightLightMediumContrast,
    surfaceContainerLowest = md_red_theme_surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = md_red_theme_surfaceContainerLowLightMediumContrast,
    surfaceContainer = md_red_theme_surfaceContainerLightMediumContrast,
    surfaceContainerHigh = md_red_theme_surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = md_red_theme_surfaceContainerHighestLightMediumContrast,
)

val RedHighContrastLightColorScheme = lightColorScheme(
    primary = md_red_theme_primaryLightHighContrast,
    onPrimary = md_red_theme_onPrimaryLightHighContrast,
    primaryContainer = md_red_theme_primaryContainerLightHighContrast,
    onPrimaryContainer = md_red_theme_onPrimaryContainerLightHighContrast,
    secondary = md_red_theme_secondaryLightHighContrast,
    onSecondary = md_red_theme_onSecondaryLightHighContrast,
    secondaryContainer = md_red_theme_secondaryContainerLightHighContrast,
    onSecondaryContainer = md_red_theme_onSecondaryContainerLightHighContrast,
    tertiary = md_red_theme_tertiaryLightHighContrast,
    onTertiary = md_red_theme_onTertiaryLightHighContrast,
    tertiaryContainer = md_red_theme_tertiaryContainerLightHighContrast,
    onTertiaryContainer = md_red_theme_onTertiaryContainerLightHighContrast,
    error = md_red_theme_errorLightHighContrast,
    onError = md_red_theme_onErrorLightHighContrast,
    errorContainer = md_red_theme_errorContainerLightHighContrast,
    onErrorContainer = md_red_theme_onErrorContainerLightHighContrast,
    background = md_red_theme_backgroundLightHighContrast,
    onBackground = md_red_theme_onBackgroundLightHighContrast,
    surface = md_red_theme_surfaceLightHighContrast,
    onSurface = md_red_theme_onSurfaceLightHighContrast,
    surfaceVariant = md_red_theme_surfaceVariantLightHighContrast,
    onSurfaceVariant = md_red_theme_onSurfaceVariantLightHighContrast,
    outline = md_red_theme_outlineLightHighContrast,
    outlineVariant = md_red_theme_outlineVariantLightHighContrast,
    scrim = md_red_theme_scrimLightHighContrast,
    inverseSurface = md_red_theme_inverseSurfaceLightHighContrast,
    inverseOnSurface = md_red_theme_inverseOnSurfaceLightHighContrast,
    inversePrimary = md_red_theme_inversePrimaryLightHighContrast,
    surfaceDim = md_red_theme_surfaceDimLightHighContrast,
    surfaceBright = md_red_theme_surfaceBrightLightHighContrast,
    surfaceContainerLowest = md_red_theme_surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = md_red_theme_surfaceContainerLowLightHighContrast,
    surfaceContainer = md_red_theme_surfaceContainerLightHighContrast,
    surfaceContainerHigh = md_red_theme_surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = md_red_theme_surfaceContainerHighestLightHighContrast,
)

val RedMediumContrastDarkColorScheme = darkColorScheme(
    primary = md_red_theme_primaryDarkMediumContrast,
    onPrimary = md_red_theme_onPrimaryDarkMediumContrast,
    primaryContainer = md_red_theme_primaryContainerDarkMediumContrast,
    onPrimaryContainer = md_red_theme_onPrimaryContainerDarkMediumContrast,
    secondary = md_red_theme_secondaryDarkMediumContrast,
    onSecondary = md_red_theme_onSecondaryDarkMediumContrast,
    secondaryContainer = md_red_theme_secondaryContainerDarkMediumContrast,
    onSecondaryContainer = md_red_theme_onSecondaryContainerDarkMediumContrast,
    tertiary = md_red_theme_tertiaryDarkMediumContrast,
    onTertiary = md_red_theme_onTertiaryDarkMediumContrast,
    tertiaryContainer = md_red_theme_tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = md_red_theme_onTertiaryContainerDarkMediumContrast,
    error = md_red_theme_errorDarkMediumContrast,
    onError = md_red_theme_onErrorDarkMediumContrast,
    errorContainer = md_red_theme_errorContainerDarkMediumContrast,
    onErrorContainer = md_red_theme_onErrorContainerDarkMediumContrast,
    background = md_red_theme_backgroundDarkMediumContrast,
    onBackground = md_red_theme_onBackgroundDarkMediumContrast,
    surface = md_red_theme_surfaceDarkMediumContrast,
    onSurface = md_red_theme_onSurfaceDarkMediumContrast,
    surfaceVariant = md_red_theme_surfaceVariantDarkMediumContrast,
    onSurfaceVariant = md_red_theme_onSurfaceVariantDarkMediumContrast,
    outline = md_red_theme_outlineDarkMediumContrast,
    outlineVariant = md_red_theme_outlineVariantDarkMediumContrast,
    scrim = md_red_theme_scrimDarkMediumContrast,
    inverseSurface = md_red_theme_inverseSurfaceDarkMediumContrast,
    inverseOnSurface = md_red_theme_inverseOnSurfaceDarkMediumContrast,
    inversePrimary = md_red_theme_inversePrimaryDarkMediumContrast,
    surfaceDim = md_red_theme_surfaceDimDarkMediumContrast,
    surfaceBright = md_red_theme_surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = md_red_theme_surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = md_red_theme_surfaceContainerLowDarkMediumContrast,
    surfaceContainer = md_red_theme_surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = md_red_theme_surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = md_red_theme_surfaceContainerHighestDarkMediumContrast,
)

val RedHighContrastDarkColorScheme = darkColorScheme(
    primary = md_red_theme_primaryDarkHighContrast,
    onPrimary = md_red_theme_onPrimaryDarkHighContrast,
    primaryContainer = md_red_theme_primaryContainerDarkHighContrast,
    onPrimaryContainer = md_red_theme_onPrimaryContainerDarkHighContrast,
    secondary = md_red_theme_secondaryDarkHighContrast,
    onSecondary = md_red_theme_onSecondaryDarkHighContrast,
    secondaryContainer = md_red_theme_secondaryContainerDarkHighContrast,
    onSecondaryContainer = md_red_theme_onSecondaryContainerDarkHighContrast,
    tertiary = md_red_theme_tertiaryDarkHighContrast,
    onTertiary = md_red_theme_onTertiaryDarkHighContrast,
    tertiaryContainer = md_red_theme_tertiaryContainerDarkHighContrast,
    onTertiaryContainer = md_red_theme_onTertiaryContainerDarkHighContrast,
    error = md_red_theme_errorDarkHighContrast,
    onError = md_red_theme_onErrorDarkHighContrast,
    errorContainer = md_red_theme_errorContainerDarkHighContrast,
    onErrorContainer = md_red_theme_onErrorContainerDarkHighContrast,
    background = md_red_theme_backgroundDarkHighContrast,
    onBackground = md_red_theme_onBackgroundDarkHighContrast,
    surface = md_red_theme_surfaceDarkHighContrast,
    onSurface = md_red_theme_onSurfaceDarkHighContrast,
    surfaceVariant = md_red_theme_surfaceVariantDarkHighContrast,
    onSurfaceVariant = md_red_theme_onSurfaceVariantDarkHighContrast,
    outline = md_red_theme_outlineDarkHighContrast,
    outlineVariant = md_red_theme_outlineVariantDarkHighContrast,
    scrim = md_red_theme_scrimDarkHighContrast,
    inverseSurface = md_red_theme_inverseSurfaceDarkHighContrast,
    inverseOnSurface = md_red_theme_inverseOnSurfaceDarkHighContrast,
    inversePrimary = md_red_theme_inversePrimaryDarkHighContrast,
    surfaceDim = md_red_theme_surfaceDimDarkHighContrast,
    surfaceBright = md_red_theme_surfaceBrightDarkHighContrast,
    surfaceContainerLowest = md_red_theme_surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = md_red_theme_surfaceContainerLowDarkHighContrast,
    surfaceContainer = md_red_theme_surfaceContainerDarkHighContrast,
    surfaceContainerHigh = md_red_theme_surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = md_red_theme_surfaceContainerHighestDarkHighContrast,
)

