package org.lyd.kmp01.designSystem.colors

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_yellow_theme_primaryLight = Color(0xFF6D5E0F)
val md_yellow_theme_onPrimaryLight = Color(0xFFFFFFFF)
val md_yellow_theme_primaryContainerLight = Color(0xFFF8E287)
val md_yellow_theme_onPrimaryContainerLight = Color(0xFF221B00)
val md_yellow_theme_secondaryLight = Color(0xFF665E40)
val md_yellow_theme_onSecondaryLight = Color(0xFFFFFFFF)
val md_yellow_theme_secondaryContainerLight = Color(0xFFEEE2BC)
val md_yellow_theme_onSecondaryContainerLight = Color(0xFF211B04)
val md_yellow_theme_tertiaryLight = Color(0xFF43664E)
val md_yellow_theme_onTertiaryLight = Color(0xFFFFFFFF)
val md_yellow_theme_tertiaryContainerLight = Color(0xFFC5ECCE)
val md_yellow_theme_onTertiaryContainerLight = Color(0xFF00210F)
val md_yellow_theme_errorLight = Color(0xFFBA1A1A)
val md_yellow_theme_onErrorLight = Color(0xFFFFFFFF)
val md_yellow_theme_errorContainerLight = Color(0xFFFFDAD6)
val md_yellow_theme_onErrorContainerLight = Color(0xFF410002)
val md_yellow_theme_backgroundLight = Color(0xFFFFF9EE)
val md_yellow_theme_onBackgroundLight = Color(0xFF1E1B13)
val md_yellow_theme_surfaceLight = Color(0xFFFFF9EE)
val md_yellow_theme_onSurfaceLight = Color(0xFF1E1B13)
val md_yellow_theme_surfaceVariantLight = Color(0xFFEAE2D0)
val md_yellow_theme_onSurfaceVariantLight = Color(0xFF4B4739)
val md_yellow_theme_outlineLight = Color(0xFF7C7767)
val md_yellow_theme_outlineVariantLight = Color(0xFFCDC6B4)
val md_yellow_theme_scrimLight = Color(0xFF000000)
val md_yellow_theme_inverseSurfaceLight = Color(0xFF333027)
val md_yellow_theme_inverseOnSurfaceLight = Color(0xFFF7F0E2)
val md_yellow_theme_inversePrimaryLight = Color(0xFFDBC66E)
val md_yellow_theme_surfaceDimLight = Color(0xFFE0D9CC)
val md_yellow_theme_surfaceBrightLight = Color(0xFFFFF9EE)
val md_yellow_theme_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val md_yellow_theme_surfaceContainerLowLight = Color(0xFFFAF3E5)
val md_yellow_theme_surfaceContainerLight = Color(0xFFF4EDDF)
val md_yellow_theme_surfaceContainerHighLight = Color(0xFFEEE8DA)
val md_yellow_theme_surfaceContainerHighestLight = Color(0xFFE8E2D4)

val md_yellow_theme_primaryLightMediumContrast = Color(0xFF4F4200)
val md_yellow_theme_onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_primaryContainerLightMediumContrast = Color(0xFF857425)
val md_yellow_theme_onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_secondaryLightMediumContrast = Color(0xFF4A4327)
val md_yellow_theme_onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_secondaryContainerLightMediumContrast = Color(0xFF7D7455)
val md_yellow_theme_onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_tertiaryLightMediumContrast = Color(0xFF284A34)
val md_yellow_theme_onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_tertiaryContainerLightMediumContrast = Color(0xFF597D64)
val md_yellow_theme_onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_errorLightMediumContrast = Color(0xFF8C0009)
val md_yellow_theme_onErrorLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_errorContainerLightMediumContrast = Color(0xFFDA342E)
val md_yellow_theme_onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_backgroundLightMediumContrast = Color(0xFFFFF9EE)
val md_yellow_theme_onBackgroundLightMediumContrast = Color(0xFF1E1B13)
val md_yellow_theme_surfaceLightMediumContrast = Color(0xFFFFF9EE)
val md_yellow_theme_onSurfaceLightMediumContrast = Color(0xFF1E1B13)
val md_yellow_theme_surfaceVariantLightMediumContrast = Color(0xFFEAE2D0)
val md_yellow_theme_onSurfaceVariantLightMediumContrast = Color(0xFF474335)
val md_yellow_theme_outlineLightMediumContrast = Color(0xFF645F50)
val md_yellow_theme_outlineVariantLightMediumContrast = Color(0xFF807A6B)
val md_yellow_theme_scrimLightMediumContrast = Color(0xFF000000)
val md_yellow_theme_inverseSurfaceLightMediumContrast = Color(0xFF333027)
val md_yellow_theme_inverseOnSurfaceLightMediumContrast = Color(0xFFF7F0E2)
val md_yellow_theme_inversePrimaryLightMediumContrast = Color(0xFFDBC66E)
val md_yellow_theme_surfaceDimLightMediumContrast = Color(0xFFE0D9CC)
val md_yellow_theme_surfaceBrightLightMediumContrast = Color(0xFFFFF9EE)
val md_yellow_theme_surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val md_yellow_theme_surfaceContainerLowLightMediumContrast = Color(0xFFFAF3E5)
val md_yellow_theme_surfaceContainerLightMediumContrast = Color(0xFFF4EDDF)
val md_yellow_theme_surfaceContainerHighLightMediumContrast = Color(0xFFEEE8DA)
val md_yellow_theme_surfaceContainerHighestLightMediumContrast = Color(0xFFE8E2D4)

val md_yellow_theme_primaryLightHighContrast = Color(0xFF292200)
val md_yellow_theme_onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_primaryContainerLightHighContrast = Color(0xFF4F4200)
val md_yellow_theme_onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_secondaryLightHighContrast = Color(0xFF282209)
val md_yellow_theme_onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_secondaryContainerLightHighContrast = Color(0xFF4A4327)
val md_yellow_theme_onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_tertiaryLightHighContrast = Color(0xFF042815)
val md_yellow_theme_onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_tertiaryContainerLightHighContrast = Color(0xFF284A34)
val md_yellow_theme_onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_errorLightHighContrast = Color(0xFF4E0002)
val md_yellow_theme_onErrorLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_errorContainerLightHighContrast = Color(0xFF8C0009)
val md_yellow_theme_onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_backgroundLightHighContrast = Color(0xFFFFF9EE)
val md_yellow_theme_onBackgroundLightHighContrast = Color(0xFF1E1B13)
val md_yellow_theme_surfaceLightHighContrast = Color(0xFFFFF9EE)
val md_yellow_theme_onSurfaceLightHighContrast = Color(0xFF000000)
val md_yellow_theme_surfaceVariantLightHighContrast = Color(0xFFEAE2D0)
val md_yellow_theme_onSurfaceVariantLightHighContrast = Color(0xFF272418)
val md_yellow_theme_outlineLightHighContrast = Color(0xFF474335)
val md_yellow_theme_outlineVariantLightHighContrast = Color(0xFF474335)
val md_yellow_theme_scrimLightHighContrast = Color(0xFF000000)
val md_yellow_theme_inverseSurfaceLightHighContrast = Color(0xFF333027)
val md_yellow_theme_inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_inversePrimaryLightHighContrast = Color(0xFFFFECA2)
val md_yellow_theme_surfaceDimLightHighContrast = Color(0xFFE0D9CC)
val md_yellow_theme_surfaceBrightLightHighContrast = Color(0xFFFFF9EE)
val md_yellow_theme_surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_surfaceContainerLowLightHighContrast = Color(0xFFFAF3E5)
val md_yellow_theme_surfaceContainerLightHighContrast = Color(0xFFF4EDDF)
val md_yellow_theme_surfaceContainerHighLightHighContrast = Color(0xFFEEE8DA)
val md_yellow_theme_surfaceContainerHighestLightHighContrast = Color(0xFFE8E2D4)

val md_yellow_theme_primaryDark = Color(0xFFDBC66E)
val md_yellow_theme_onPrimaryDark = Color(0xFF3A3000)
val md_yellow_theme_primaryContainerDark = Color(0xFF534600)
val md_yellow_theme_onPrimaryContainerDark = Color(0xFFF8E287)
val md_yellow_theme_secondaryDark = Color(0xFFD1C6A1)
val md_yellow_theme_onSecondaryDark = Color(0xFF363016)
val md_yellow_theme_secondaryContainerDark = Color(0xFF4E472A)
val md_yellow_theme_onSecondaryContainerDark = Color(0xFFEEE2BC)
val md_yellow_theme_tertiaryDark = Color(0xFFA9D0B3)
val md_yellow_theme_onTertiaryDark = Color(0xFF143723)
val md_yellow_theme_tertiaryContainerDark = Color(0xFF2C4E38)
val md_yellow_theme_onTertiaryContainerDark = Color(0xFFC5ECCE)
val md_yellow_theme_errorDark = Color(0xFFFFB4AB)
val md_yellow_theme_onErrorDark = Color(0xFF690005)
val md_yellow_theme_errorContainerDark = Color(0xFF93000A)
val md_yellow_theme_onErrorContainerDark = Color(0xFFFFDAD6)
val md_yellow_theme_backgroundDark = Color(0xFF15130B)
val md_yellow_theme_onBackgroundDark = Color(0xFFE8E2D4)
val md_yellow_theme_surfaceDark = Color(0xFF15130B)
val md_yellow_theme_onSurfaceDark = Color(0xFFE8E2D4)
val md_yellow_theme_surfaceVariantDark = Color(0xFF4B4739)
val md_yellow_theme_onSurfaceVariantDark = Color(0xFFCDC6B4)
val md_yellow_theme_outlineDark = Color(0xFF969080)
val md_yellow_theme_outlineVariantDark = Color(0xFF4B4739)
val md_yellow_theme_scrimDark = Color(0xFF000000)
val md_yellow_theme_inverseSurfaceDark = Color(0xFFE8E2D4)
val md_yellow_theme_inverseOnSurfaceDark = Color(0xFF333027)
val md_yellow_theme_inversePrimaryDark = Color(0xFF6D5E0F)
val md_yellow_theme_surfaceDimDark = Color(0xFF15130B)
val md_yellow_theme_surfaceBrightDark = Color(0xFF3C3930)
val md_yellow_theme_surfaceContainerLowestDark = Color(0xFF100E07)
val md_yellow_theme_surfaceContainerLowDark = Color(0xFF1E1B13)
val md_yellow_theme_surfaceContainerDark = Color(0xFF222017)
val md_yellow_theme_surfaceContainerHighDark = Color(0xFF2D2A21)
val md_yellow_theme_surfaceContainerHighestDark = Color(0xFF38352B)

val md_yellow_theme_primaryDarkMediumContrast = Color(0xFFE0CA72)
val md_yellow_theme_onPrimaryDarkMediumContrast = Color(0xFF1C1600)
val md_yellow_theme_primaryContainerDarkMediumContrast = Color(0xFFA3903F)
val md_yellow_theme_onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val md_yellow_theme_secondaryDarkMediumContrast = Color(0xFFD6CAA5)
val md_yellow_theme_onSecondaryDarkMediumContrast = Color(0xFF1B1602)
val md_yellow_theme_secondaryContainerDarkMediumContrast = Color(0xFF9A916F)
val md_yellow_theme_onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val md_yellow_theme_tertiaryDarkMediumContrast = Color(0xFFADD4B7)
val md_yellow_theme_onTertiaryDarkMediumContrast = Color(0xFF001B0C)
val md_yellow_theme_tertiaryContainerDarkMediumContrast = Color(0xFF75997F)
val md_yellow_theme_onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val md_yellow_theme_errorDarkMediumContrast = Color(0xFFFFBAB1)
val md_yellow_theme_onErrorDarkMediumContrast = Color(0xFF370001)
val md_yellow_theme_errorContainerDarkMediumContrast = Color(0xFFFF5449)
val md_yellow_theme_onErrorContainerDarkMediumContrast = Color(0xFF000000)
val md_yellow_theme_backgroundDarkMediumContrast = Color(0xFF15130B)
val md_yellow_theme_onBackgroundDarkMediumContrast = Color(0xFFE8E2D4)
val md_yellow_theme_surfaceDarkMediumContrast = Color(0xFF15130B)
val md_yellow_theme_onSurfaceDarkMediumContrast = Color(0xFFFFFAF5)
val md_yellow_theme_surfaceVariantDarkMediumContrast = Color(0xFF4B4739)
val md_yellow_theme_onSurfaceVariantDarkMediumContrast = Color(0xFFD1CAB8)
val md_yellow_theme_outlineDarkMediumContrast = Color(0xFFA9A292)
val md_yellow_theme_outlineVariantDarkMediumContrast = Color(0xFF888373)
val md_yellow_theme_scrimDarkMediumContrast = Color(0xFF000000)
val md_yellow_theme_inverseSurfaceDarkMediumContrast = Color(0xFFE8E2D4)
val md_yellow_theme_inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
val md_yellow_theme_inversePrimaryDarkMediumContrast = Color(0xFF554700)
val md_yellow_theme_surfaceDimDarkMediumContrast = Color(0xFF15130B)
val md_yellow_theme_surfaceBrightDarkMediumContrast = Color(0xFF3C3930)
val md_yellow_theme_surfaceContainerLowestDarkMediumContrast = Color(0xFF100E07)
val md_yellow_theme_surfaceContainerLowDarkMediumContrast = Color(0xFF1E1B13)
val md_yellow_theme_surfaceContainerDarkMediumContrast = Color(0xFF222017)
val md_yellow_theme_surfaceContainerHighDarkMediumContrast = Color(0xFF2D2A21)
val md_yellow_theme_surfaceContainerHighestDarkMediumContrast = Color(0xFF38352B)

val md_yellow_theme_primaryDarkHighContrast = Color(0xFFFFFAF5)
val md_yellow_theme_onPrimaryDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_primaryContainerDarkHighContrast = Color(0xFFE0CA72)
val md_yellow_theme_onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_secondaryDarkHighContrast = Color(0xFFFFFAF5)
val md_yellow_theme_onSecondaryDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_secondaryContainerDarkHighContrast = Color(0xFFD6CAA5)
val md_yellow_theme_onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_tertiaryDarkHighContrast = Color(0xFFEFFFF0)
val md_yellow_theme_onTertiaryDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_tertiaryContainerDarkHighContrast = Color(0xFFADD4B7)
val md_yellow_theme_onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_errorDarkHighContrast = Color(0xFFFFF9F9)
val md_yellow_theme_onErrorDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val md_yellow_theme_onErrorContainerDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_backgroundDarkHighContrast = Color(0xFF15130B)
val md_yellow_theme_onBackgroundDarkHighContrast = Color(0xFFE8E2D4)
val md_yellow_theme_surfaceDarkHighContrast = Color(0xFF15130B)
val md_yellow_theme_onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val md_yellow_theme_surfaceVariantDarkHighContrast = Color(0xFF4B4739)
val md_yellow_theme_onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF5)
val md_yellow_theme_outlineDarkHighContrast = Color(0xFFD1CAB8)
val md_yellow_theme_outlineVariantDarkHighContrast = Color(0xFFD1CAB8)
val md_yellow_theme_scrimDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_inverseSurfaceDarkHighContrast = Color(0xFFE8E2D4)
val md_yellow_theme_inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val md_yellow_theme_inversePrimaryDarkHighContrast = Color(0xFF322A00)
val md_yellow_theme_surfaceDimDarkHighContrast = Color(0xFF15130B)
val md_yellow_theme_surfaceBrightDarkHighContrast = Color(0xFF3C3930)
val md_yellow_theme_surfaceContainerLowestDarkHighContrast = Color(0xFF100E07)
val md_yellow_theme_surfaceContainerLowDarkHighContrast = Color(0xFF1E1B13)
val md_yellow_theme_surfaceContainerDarkHighContrast = Color(0xFF222017)
val md_yellow_theme_surfaceContainerHighDarkHighContrast = Color(0xFF2D2A21)
val md_yellow_theme_surfaceContainerHighestDarkHighContrast = Color(0xFF38352B)

val YellowLightScheme = lightColorScheme(
    primary = md_yellow_theme_primaryLight,
    onPrimary = md_yellow_theme_onPrimaryLight,
    primaryContainer = md_yellow_theme_primaryContainerLight,
    onPrimaryContainer = md_yellow_theme_onPrimaryContainerLight,
    secondary = md_yellow_theme_secondaryLight,
    onSecondary = md_yellow_theme_onSecondaryLight,
    secondaryContainer = md_yellow_theme_secondaryContainerLight,
    onSecondaryContainer = md_yellow_theme_onSecondaryContainerLight,
    tertiary = md_yellow_theme_tertiaryLight,
    onTertiary = md_yellow_theme_onTertiaryLight,
    tertiaryContainer = md_yellow_theme_tertiaryContainerLight,
    onTertiaryContainer = md_yellow_theme_onTertiaryContainerLight,
    error = md_yellow_theme_errorLight,
    onError = md_yellow_theme_onErrorLight,
    errorContainer = md_yellow_theme_errorContainerLight,
    onErrorContainer = md_yellow_theme_onErrorContainerLight,
    background = md_yellow_theme_backgroundLight,
    onBackground = md_yellow_theme_onBackgroundLight,
    surface = md_yellow_theme_surfaceLight,
    onSurface = md_yellow_theme_onSurfaceLight,
    surfaceVariant = md_yellow_theme_surfaceVariantLight,
    onSurfaceVariant = md_yellow_theme_onSurfaceVariantLight,
    outline = md_yellow_theme_outlineLight,
    outlineVariant = md_yellow_theme_outlineVariantLight,
    scrim = md_yellow_theme_scrimLight,
    inverseSurface = md_yellow_theme_inverseSurfaceLight,
    inverseOnSurface = md_yellow_theme_inverseOnSurfaceLight,
    inversePrimary = md_yellow_theme_inversePrimaryLight,
    surfaceDim = md_yellow_theme_surfaceDimLight,
    surfaceBright = md_yellow_theme_surfaceBrightLight,
    surfaceContainerLowest = md_yellow_theme_surfaceContainerLowestLight,
    surfaceContainerLow = md_yellow_theme_surfaceContainerLowLight,
    surfaceContainer = md_yellow_theme_surfaceContainerLight,
    surfaceContainerHigh = md_yellow_theme_surfaceContainerHighLight,
    surfaceContainerHighest = md_yellow_theme_surfaceContainerHighestLight,
)

val YellowDarkScheme = darkColorScheme(
    primary = md_yellow_theme_primaryDark,
    onPrimary = md_yellow_theme_onPrimaryDark,
    primaryContainer = md_yellow_theme_primaryContainerDark,
    onPrimaryContainer = md_yellow_theme_onPrimaryContainerDark,
    secondary = md_yellow_theme_secondaryDark,
    onSecondary = md_yellow_theme_onSecondaryDark,
    secondaryContainer = md_yellow_theme_secondaryContainerDark,
    onSecondaryContainer = md_yellow_theme_onSecondaryContainerDark,
    tertiary = md_yellow_theme_tertiaryDark,
    onTertiary = md_yellow_theme_onTertiaryDark,
    tertiaryContainer = md_yellow_theme_tertiaryContainerDark,
    onTertiaryContainer = md_yellow_theme_onTertiaryContainerDark,
    error = md_yellow_theme_errorDark,
    onError = md_yellow_theme_onErrorDark,
    errorContainer = md_yellow_theme_errorContainerDark,
    onErrorContainer = md_yellow_theme_onErrorContainerDark,
    background = md_yellow_theme_backgroundDark,
    onBackground = md_yellow_theme_onBackgroundDark,
    surface = md_yellow_theme_surfaceDark,
    onSurface = md_yellow_theme_onSurfaceDark,
    surfaceVariant = md_yellow_theme_surfaceVariantDark,
    onSurfaceVariant = md_yellow_theme_onSurfaceVariantDark,
    outline = md_yellow_theme_outlineDark,
    outlineVariant = md_yellow_theme_outlineVariantDark,
    scrim = md_yellow_theme_scrimDark,
    inverseSurface = md_yellow_theme_inverseSurfaceDark,
    inverseOnSurface = md_yellow_theme_inverseOnSurfaceDark,
    inversePrimary = md_yellow_theme_inversePrimaryDark,
    surfaceDim = md_yellow_theme_surfaceDimDark,
    surfaceBright = md_yellow_theme_surfaceBrightDark,
    surfaceContainerLowest = md_yellow_theme_surfaceContainerLowestDark,
    surfaceContainerLow = md_yellow_theme_surfaceContainerLowDark,
    surfaceContainer = md_yellow_theme_surfaceContainerDark,
    surfaceContainerHigh = md_yellow_theme_surfaceContainerHighDark,
    surfaceContainerHighest = md_yellow_theme_surfaceContainerHighestDark,
)

val YellowMediumContrastLightColorScheme = lightColorScheme(
    primary = md_yellow_theme_primaryLightMediumContrast,
    onPrimary = md_yellow_theme_onPrimaryLightMediumContrast,
    primaryContainer = md_yellow_theme_primaryContainerLightMediumContrast,
    onPrimaryContainer = md_yellow_theme_onPrimaryContainerLightMediumContrast,
    secondary = md_yellow_theme_secondaryLightMediumContrast,
    onSecondary = md_yellow_theme_onSecondaryLightMediumContrast,
    secondaryContainer = md_yellow_theme_secondaryContainerLightMediumContrast,
    onSecondaryContainer = md_yellow_theme_onSecondaryContainerLightMediumContrast,
    tertiary = md_yellow_theme_tertiaryLightMediumContrast,
    onTertiary = md_yellow_theme_onTertiaryLightMediumContrast,
    tertiaryContainer = md_yellow_theme_tertiaryContainerLightMediumContrast,
    onTertiaryContainer = md_yellow_theme_onTertiaryContainerLightMediumContrast,
    error = md_yellow_theme_errorLightMediumContrast,
    onError = md_yellow_theme_onErrorLightMediumContrast,
    errorContainer = md_yellow_theme_errorContainerLightMediumContrast,
    onErrorContainer = md_yellow_theme_onErrorContainerLightMediumContrast,
    background = md_yellow_theme_backgroundLightMediumContrast,
    onBackground = md_yellow_theme_onBackgroundLightMediumContrast,
    surface = md_yellow_theme_surfaceLightMediumContrast,
    onSurface = md_yellow_theme_onSurfaceLightMediumContrast,
    surfaceVariant = md_yellow_theme_surfaceVariantLightMediumContrast,
    onSurfaceVariant = md_yellow_theme_onSurfaceVariantLightMediumContrast,
    outline = md_yellow_theme_outlineLightMediumContrast,
    outlineVariant = md_yellow_theme_outlineVariantLightMediumContrast,
    scrim = md_yellow_theme_scrimLightMediumContrast,
    inverseSurface = md_yellow_theme_inverseSurfaceLightMediumContrast,
    inverseOnSurface = md_yellow_theme_inverseOnSurfaceLightMediumContrast,
    inversePrimary = md_yellow_theme_inversePrimaryLightMediumContrast,
    surfaceDim = md_yellow_theme_surfaceDimLightMediumContrast,
    surfaceBright = md_yellow_theme_surfaceBrightLightMediumContrast,
    surfaceContainerLowest = md_yellow_theme_surfaceContainerLowestLightMediumContrast,
    surfaceContainerLow = md_yellow_theme_surfaceContainerLowLightMediumContrast,
    surfaceContainer = md_yellow_theme_surfaceContainerLightMediumContrast,
    surfaceContainerHigh = md_yellow_theme_surfaceContainerHighLightMediumContrast,
    surfaceContainerHighest = md_yellow_theme_surfaceContainerHighestLightMediumContrast,
)

val YellowHighContrastLightColorScheme = lightColorScheme(
    primary = md_yellow_theme_primaryLightHighContrast,
    onPrimary = md_yellow_theme_onPrimaryLightHighContrast,
    primaryContainer = md_yellow_theme_primaryContainerLightHighContrast,
    onPrimaryContainer = md_yellow_theme_onPrimaryContainerLightHighContrast,
    secondary = md_yellow_theme_secondaryLightHighContrast,
    onSecondary = md_yellow_theme_onSecondaryLightHighContrast,
    secondaryContainer = md_yellow_theme_secondaryContainerLightHighContrast,
    onSecondaryContainer = md_yellow_theme_onSecondaryContainerLightHighContrast,
    tertiary = md_yellow_theme_tertiaryLightHighContrast,
    onTertiary = md_yellow_theme_onTertiaryLightHighContrast,
    tertiaryContainer = md_yellow_theme_tertiaryContainerLightHighContrast,
    onTertiaryContainer = md_yellow_theme_onTertiaryContainerLightHighContrast,
    error = md_yellow_theme_errorLightHighContrast,
    onError = md_yellow_theme_onErrorLightHighContrast,
    errorContainer = md_yellow_theme_errorContainerLightHighContrast,
    onErrorContainer = md_yellow_theme_onErrorContainerLightHighContrast,
    background = md_yellow_theme_backgroundLightHighContrast,
    onBackground = md_yellow_theme_onBackgroundLightHighContrast,
    surface = md_yellow_theme_surfaceLightHighContrast,
    onSurface = md_yellow_theme_onSurfaceLightHighContrast,
    surfaceVariant = md_yellow_theme_surfaceVariantLightHighContrast,
    onSurfaceVariant = md_yellow_theme_onSurfaceVariantLightHighContrast,
    outline = md_yellow_theme_outlineLightHighContrast,
    outlineVariant = md_yellow_theme_outlineVariantLightHighContrast,
    scrim = md_yellow_theme_scrimLightHighContrast,
    inverseSurface = md_yellow_theme_inverseSurfaceLightHighContrast,
    inverseOnSurface = md_yellow_theme_inverseOnSurfaceLightHighContrast,
    inversePrimary = md_yellow_theme_inversePrimaryLightHighContrast,
    surfaceDim = md_yellow_theme_surfaceDimLightHighContrast,
    surfaceBright = md_yellow_theme_surfaceBrightLightHighContrast,
    surfaceContainerLowest = md_yellow_theme_surfaceContainerLowestLightHighContrast,
    surfaceContainerLow = md_yellow_theme_surfaceContainerLowLightHighContrast,
    surfaceContainer = md_yellow_theme_surfaceContainerLightHighContrast,
    surfaceContainerHigh = md_yellow_theme_surfaceContainerHighLightHighContrast,
    surfaceContainerHighest = md_yellow_theme_surfaceContainerHighestLightHighContrast,
)

val YellowMediumContrastDarkColorScheme = darkColorScheme(
    primary = md_yellow_theme_primaryDarkMediumContrast,
    onPrimary = md_yellow_theme_onPrimaryDarkMediumContrast,
    primaryContainer = md_yellow_theme_primaryContainerDarkMediumContrast,
    onPrimaryContainer = md_yellow_theme_onPrimaryContainerDarkMediumContrast,
    secondary = md_yellow_theme_secondaryDarkMediumContrast,
    onSecondary = md_yellow_theme_onSecondaryDarkMediumContrast,
    secondaryContainer = md_yellow_theme_secondaryContainerDarkMediumContrast,
    onSecondaryContainer = md_yellow_theme_onSecondaryContainerDarkMediumContrast,
    tertiary = md_yellow_theme_tertiaryDarkMediumContrast,
    onTertiary = md_yellow_theme_onTertiaryDarkMediumContrast,
    tertiaryContainer = md_yellow_theme_tertiaryContainerDarkMediumContrast,
    onTertiaryContainer = md_yellow_theme_onTertiaryContainerDarkMediumContrast,
    error = md_yellow_theme_errorDarkMediumContrast,
    onError = md_yellow_theme_onErrorDarkMediumContrast,
    errorContainer = md_yellow_theme_errorContainerDarkMediumContrast,
    onErrorContainer = md_yellow_theme_onErrorContainerDarkMediumContrast,
    background = md_yellow_theme_backgroundDarkMediumContrast,
    onBackground = md_yellow_theme_onBackgroundDarkMediumContrast,
    surface = md_yellow_theme_surfaceDarkMediumContrast,
    onSurface = md_yellow_theme_onSurfaceDarkMediumContrast,
    surfaceVariant = md_yellow_theme_surfaceVariantDarkMediumContrast,
    onSurfaceVariant = md_yellow_theme_onSurfaceVariantDarkMediumContrast,
    outline = md_yellow_theme_outlineDarkMediumContrast,
    outlineVariant = md_yellow_theme_outlineVariantDarkMediumContrast,
    scrim = md_yellow_theme_scrimDarkMediumContrast,
    inverseSurface = md_yellow_theme_inverseSurfaceDarkMediumContrast,
    inverseOnSurface = md_yellow_theme_inverseOnSurfaceDarkMediumContrast,
    inversePrimary = md_yellow_theme_inversePrimaryDarkMediumContrast,
    surfaceDim = md_yellow_theme_surfaceDimDarkMediumContrast,
    surfaceBright = md_yellow_theme_surfaceBrightDarkMediumContrast,
    surfaceContainerLowest = md_yellow_theme_surfaceContainerLowestDarkMediumContrast,
    surfaceContainerLow = md_yellow_theme_surfaceContainerLowDarkMediumContrast,
    surfaceContainer = md_yellow_theme_surfaceContainerDarkMediumContrast,
    surfaceContainerHigh = md_yellow_theme_surfaceContainerHighDarkMediumContrast,
    surfaceContainerHighest = md_yellow_theme_surfaceContainerHighestDarkMediumContrast,
)

val YellowHighContrastDarkColorScheme = darkColorScheme(
    primary = md_yellow_theme_primaryDarkHighContrast,
    onPrimary = md_yellow_theme_onPrimaryDarkHighContrast,
    primaryContainer = md_yellow_theme_primaryContainerDarkHighContrast,
    onPrimaryContainer = md_yellow_theme_onPrimaryContainerDarkHighContrast,
    secondary = md_yellow_theme_secondaryDarkHighContrast,
    onSecondary = md_yellow_theme_onSecondaryDarkHighContrast,
    secondaryContainer = md_yellow_theme_secondaryContainerDarkHighContrast,
    onSecondaryContainer = md_yellow_theme_onSecondaryContainerDarkHighContrast,
    tertiary = md_yellow_theme_tertiaryDarkHighContrast,
    onTertiary = md_yellow_theme_onTertiaryDarkHighContrast,
    tertiaryContainer = md_yellow_theme_tertiaryContainerDarkHighContrast,
    onTertiaryContainer = md_yellow_theme_onTertiaryContainerDarkHighContrast,
    error = md_yellow_theme_errorDarkHighContrast,
    onError = md_yellow_theme_onErrorDarkHighContrast,
    errorContainer = md_yellow_theme_errorContainerDarkHighContrast,
    onErrorContainer = md_yellow_theme_onErrorContainerDarkHighContrast,
    background = md_yellow_theme_backgroundDarkHighContrast,
    onBackground = md_yellow_theme_onBackgroundDarkHighContrast,
    surface = md_yellow_theme_surfaceDarkHighContrast,
    onSurface = md_yellow_theme_onSurfaceDarkHighContrast,
    surfaceVariant = md_yellow_theme_surfaceVariantDarkHighContrast,
    onSurfaceVariant = md_yellow_theme_onSurfaceVariantDarkHighContrast,
    outline = md_yellow_theme_outlineDarkHighContrast,
    outlineVariant = md_yellow_theme_outlineVariantDarkHighContrast,
    scrim = md_yellow_theme_scrimDarkHighContrast,
    inverseSurface = md_yellow_theme_inverseSurfaceDarkHighContrast,
    inverseOnSurface = md_yellow_theme_inverseOnSurfaceDarkHighContrast,
    inversePrimary = md_yellow_theme_inversePrimaryDarkHighContrast,
    surfaceDim = md_yellow_theme_surfaceDimDarkHighContrast,
    surfaceBright = md_yellow_theme_surfaceBrightDarkHighContrast,
    surfaceContainerLowest = md_yellow_theme_surfaceContainerLowestDarkHighContrast,
    surfaceContainerLow = md_yellow_theme_surfaceContainerLowDarkHighContrast,
    surfaceContainer = md_yellow_theme_surfaceContainerDarkHighContrast,
    surfaceContainerHigh = md_yellow_theme_surfaceContainerHighDarkHighContrast,
    surfaceContainerHighest = md_yellow_theme_surfaceContainerHighestDarkHighContrast,
)

